/* Echo 英語 — 擴充句庫
   bl 欄位＝填空模式要挖掉的字（沒寫的話系統會自動挑最難的字）
*/
window.BANK = (window.BANK||[]).concat([

/* ============ 日常會話 · 擴充 ============ */
{id:"d081",en:"Could you walk me through this again?",zh:"可以再帶我走一次流程嗎？",cat:"daily",sc:"工作",lv:2,note:"walk someone through = 一步步帶著說明"},
{id:"d082",en:"I'll take care of it before the deadline.",zh:"我會在期限前處理好。",cat:"daily",sc:"工作",lv:2},
{id:"d083",en:"Let's touch base again on Thursday.",zh:"我們週四再對一次進度。",cat:"daily",sc:"工作",lv:3,note:"touch base = 簡短同步一下"},
{id:"d084",en:"I'm swamped this week.",zh:"我這週忙翻了。",cat:"daily",sc:"工作",lv:2,note:"swamped = 忙到淹沒"},
{id:"d085",en:"Do you have a minute?",zh:"你現在方便嗎？",cat:"daily",sc:"工作",lv:1},
{id:"d086",en:"I'll loop you in on the email.",zh:"我會把你加進郵件討論。",cat:"daily",sc:"工作",lv:3,note:"loop someone in = 讓某人加入資訊圈"},
{id:"d087",en:"That's out of my hands, unfortunately.",zh:"很遺憾那不是我能決定的。",cat:"daily",sc:"工作",lv:3,note:"out of my hands = 不在我掌控範圍"},
{id:"d088",en:"Could you send me the file by end of day?",zh:"可以在今天下班前把檔案寄給我嗎？",cat:"daily",sc:"工作",lv:2},
{id:"d089",en:"I'm still waiting to hear back from them.",zh:"我還在等他們回覆。",cat:"daily",sc:"工作",lv:2,note:"hear back from = 收到某人回覆"},
{id:"d090",en:"Let me double-check and confirm with you.",zh:"我再確認一次然後回覆你。",cat:"daily",sc:"工作",lv:2},

{id:"d091",en:"My phone keeps freezing lately.",zh:"我手機最近一直當機。",cat:"daily",sc:"科技",lv:2,note:"keep + Ving = 一直反覆發生"},
{id:"d092",en:"The Wi-Fi keeps dropping out.",zh:"Wi-Fi 一直斷線。",cat:"daily",sc:"科技",lv:2},
{id:"d093",en:"Could you send me the link again?",zh:"可以再傳一次連結給我嗎？",cat:"daily",sc:"科技",lv:1},
{id:"d094",en:"I accidentally deleted the file.",zh:"我不小心把檔案刪掉了。",cat:"daily",sc:"科技",lv:2},
{id:"d095",en:"Try restarting it and see if that helps.",zh:"試著重開看看有沒有用。",cat:"daily",sc:"科技",lv:2},
{id:"d096",en:"I'll share my screen so you can see.",zh:"我分享畫面給你看。",cat:"daily",sc:"科技",lv:2},
{id:"d097",en:"The app crashes every time I open it.",zh:"這個 App 每次一開就閃退。",cat:"daily",sc:"科技",lv:2},
{id:"d098",en:"I forgot my password again.",zh:"我又忘記密碼了。",cat:"daily",sc:"科技",lv:1},

{id:"d099",en:"I missed the last train home.",zh:"我錯過最後一班回家的車。",cat:"daily",sc:"通勤",lv:1},
{id:"d100",en:"Traffic was terrible this morning.",zh:"今天早上塞爆了。",cat:"daily",sc:"通勤",lv:1},
{id:"d101",en:"It usually takes me forty minutes to commute.",zh:"我通勤通常要四十分鐘。",cat:"daily",sc:"通勤",lv:2},
{id:"d102",en:"I'd rather walk than wait for the bus.",zh:"我寧願走路也不要等公車。",cat:"daily",sc:"通勤",lv:2},
{id:"d103",en:"Could you move over a little?",zh:"可以往旁邊挪一點嗎？",cat:"daily",sc:"通勤",lv:1},
{id:"d104",en:"The train is running about ten minutes late.",zh:"火車誤點大約十分鐘。",cat:"daily",sc:"通勤",lv:2,note:"running late = 誤點、遲了"},
{id:"d105",en:"I got stuck in traffic on the way here.",zh:"我來的路上塞在車陣裡。",cat:"daily",sc:"通勤",lv:2,note:"get stuck in traffic = 卡在車陣"},
{id:"d106",en:"Is this seat taken?",zh:"這個位子有人坐嗎？",cat:"daily",sc:"通勤",lv:1},

{id:"d107",en:"I'm feeling a bit under the weather today.",zh:"我今天有點不舒服。",cat:"daily",sc:"情緒",lv:3,note:"under the weather = 身體不適（跟天氣無關）"},
{id:"d108",en:"That really made my day.",zh:"那真的讓我很開心。",cat:"daily",sc:"情緒",lv:2,note:"make one's day = 讓某人一天都變好"},
{id:"d109",en:"I've been stressed out about work lately.",zh:"我最近因為工作壓力很大。",cat:"daily",sc:"情緒",lv:2},
{id:"d110",en:"Don't worry, it's not a big deal.",zh:"別擔心，這沒什麼大不了的。",cat:"daily",sc:"情緒",lv:1},
{id:"d111",en:"I'm so relieved to hear that.",zh:"聽到這個我鬆了一口氣。",cat:"daily",sc:"情緒",lv:2,note:"relieved = 鬆一口氣的"},
{id:"d112",en:"I felt terrible about forgetting your birthday.",zh:"忘記你生日讓我很過意不去。",cat:"daily",sc:"情緒",lv:3,note:"feel terrible about + Ving"},
{id:"d113",en:"It's frustrating when nobody replies.",zh:"沒人回覆的時候真的很讓人洩氣。",cat:"daily",sc:"情緒",lv:2},
{id:"d114",en:"I need some time to myself.",zh:"我需要一點自己的時間。",cat:"daily",sc:"情緒",lv:1},
{id:"d115",en:"You have nothing to be sorry for.",zh:"你完全不需要道歉。",cat:"daily",sc:"情緒",lv:2},
{id:"d116",en:"I'm proud of how far you've come.",zh:"我為你走到今天感到驕傲。",cat:"daily",sc:"情緒",lv:3,note:"how far you've come = 你走了多遠、進步多少"},

{id:"d117",en:"Do you want to grab a coffee sometime?",zh:"要不要找時間去喝杯咖啡？",cat:"daily",sc:"社交",lv:1,note:"grab a coffee = 隨意去喝杯咖啡"},
{id:"d118",en:"We should hang out more often.",zh:"我們應該多聚一聚。",cat:"daily",sc:"社交",lv:1,note:"hang out = 一起消磨時間"},
{id:"d119",en:"I'd love to, but I already have plans.",zh:"我很想去，但我已經有約了。",cat:"daily",sc:"社交",lv:2,note:"最好用的婉拒句"},
{id:"d120",en:"Feel free to bring a friend.",zh:"你可以帶朋友一起來。",cat:"daily",sc:"社交",lv:2,note:"feel free to = 儘管…沒關係"},
{id:"d121",en:"It's on me tonight.",zh:"今晚我請客。",cat:"daily",sc:"社交",lv:2,note:"It's on me = 我買單"},
{id:"d122",en:"Let's split the bill.",zh:"我們各付各的吧。",cat:"daily",sc:"社交",lv:1,note:"split the bill = 分攤帳單"},
{id:"d123",en:"Thanks for having me over.",zh:"謝謝你邀我來。",cat:"daily",sc:"社交",lv:2,note:"have someone over = 邀請某人來家裡"},
{id:"d124",en:"I had a great time tonight.",zh:"今晚我玩得很開心。",cat:"daily",sc:"社交",lv:1},

{id:"d125",en:"Could you take out the trash?",zh:"可以幫忙倒垃圾嗎？",cat:"daily",sc:"居家",lv:1},
{id:"d126",en:"Dinner will be ready in ten minutes.",zh:"晚餐十分鐘後好。",cat:"daily",sc:"居家",lv:1},
{id:"d127",en:"I'm going to the store. Do you need anything?",zh:"我要去商店，你需要什麼嗎？",cat:"daily",sc:"居家",lv:1},
{id:"d128",en:"The sink is clogged again.",zh:"水槽又堵住了。",cat:"daily",sc:"居家",lv:2,note:"clogged = 堵塞的"},
{id:"d129",en:"Have you seen my keys anywhere?",zh:"你有在哪裡看到我的鑰匙嗎？",cat:"daily",sc:"居家",lv:1},
{id:"d130",en:"I'll pick the kids up after work.",zh:"我下班後去接小孩。",cat:"daily",sc:"居家",lv:2,note:"pick up = 接（人）"},
{id:"d131",en:"We're running low on milk.",zh:"牛奶快沒了。",cat:"daily",sc:"居家",lv:2,note:"run low on = 快用完"},
{id:"d132",en:"Could you turn the volume down a bit?",zh:"可以把音量調小一點嗎？",cat:"daily",sc:"居家",lv:1},

{id:"d133",en:"I try to work out three times a week.",zh:"我盡量一週運動三次。",cat:"daily",sc:"運動健康",lv:2},
{id:"d134",en:"I pulled a muscle in my back.",zh:"我背部拉傷了。",cat:"daily",sc:"運動健康",lv:2,note:"pull a muscle = 拉傷肌肉"},
{id:"d135",en:"I've been trying to cut back on sugar.",zh:"我最近在減少糖分攝取。",cat:"daily",sc:"運動健康",lv:3,note:"cut back on = 減少（攝取／花費）"},
{id:"d136",en:"I usually go for a run before breakfast.",zh:"我通常早餐前去跑步。",cat:"daily",sc:"運動健康",lv:1},
{id:"d137",en:"I haven't been sleeping well lately.",zh:"我最近睡不太好。",cat:"daily",sc:"運動健康",lv:2},
{id:"d138",en:"You should really see a doctor about that.",zh:"那個你真的應該去看醫生。",cat:"daily",sc:"運動健康",lv:2},
{id:"d139",en:"I'm trying to drink more water every day.",zh:"我在努力每天多喝水。",cat:"daily",sc:"運動健康",lv:1},
{id:"d140",en:"My legs are so sore from yesterday.",zh:"我的腿因為昨天而超痠。",cat:"daily",sc:"運動健康",lv:2,note:"sore = 痠痛的"},

{id:"d141",en:"That's a bit out of my budget.",zh:"那有點超出我的預算。",cat:"daily",sc:"金錢",lv:2},
{id:"d142",en:"I'm trying to save up for a trip.",zh:"我在存錢去旅行。",cat:"daily",sc:"金錢",lv:2,note:"save up for = 為某事存錢"},
{id:"d143",en:"Can I pay you back next week?",zh:"我下週還你可以嗎？",cat:"daily",sc:"金錢",lv:1,note:"pay someone back = 還錢給某人"},
{id:"d144",en:"It's not worth the money, honestly.",zh:"老實說那不值那個錢。",cat:"daily",sc:"金錢",lv:2},
{id:"d145",en:"They charge extra for delivery.",zh:"他們外送要另外收費。",cat:"daily",sc:"金錢",lv:2,note:"charge extra = 額外收費"},
{id:"d146",en:"I finally paid off my loan.",zh:"我終於把貸款還清了。",cat:"daily",sc:"金錢",lv:2,note:"pay off = 還清"},

{id:"d147",en:"I'm trying to improve my English speaking.",zh:"我在努力加強我的英文口說。",cat:"daily",sc:"學習",lv:1},
{id:"d148",en:"Could you correct me if I say something wrong?",zh:"我說錯的話可以糾正我嗎？",cat:"daily",sc:"學習",lv:2},
{id:"d149",en:"How do you say this in English?",zh:"這個英文怎麼說？",cat:"daily",sc:"學習",lv:1},
{id:"d150",en:"What's the difference between these two words?",zh:"這兩個字差在哪裡？",cat:"daily",sc:"學習",lv:2},
{id:"d151",en:"I keep making the same mistake.",zh:"我一直犯同樣的錯。",cat:"daily",sc:"學習",lv:1},
{id:"d152",en:"I understand it, but I can't say it fluently yet.",zh:"我聽得懂，但還說不流利。",cat:"daily",sc:"學習",lv:3},

{id:"d153",en:"I'm sorry, I completely forgot about it.",zh:"抱歉，我完全忘記這件事了。",cat:"daily",sc:"抱怨道歉",lv:1},
{id:"d154",en:"That's not what I meant.",zh:"我不是那個意思。",cat:"daily",sc:"抱怨道歉",lv:1},
{id:"d155",en:"I think there's been a misunderstanding.",zh:"我想這中間有誤會。",cat:"daily",sc:"抱怨道歉",lv:3,note:"there's been = there has been，現在完成式"},
{id:"d156",en:"I've been waiting for over twenty minutes.",zh:"我已經等超過二十分鐘了。",cat:"daily",sc:"抱怨道歉",lv:2},
{id:"d157",en:"This isn't what I ordered.",zh:"這不是我點的。",cat:"daily",sc:"抱怨道歉",lv:1},
{id:"d158",en:"Could you check it again for me?",zh:"可以幫我再確認一次嗎？",cat:"daily",sc:"抱怨道歉",lv:1},
{id:"d159",en:"I'd like to speak to the manager, please.",zh:"我想跟經理談談。",cat:"daily",sc:"抱怨道歉",lv:2},
{id:"d160",en:"It won't happen again, I promise.",zh:"我保證不會再發生了。",cat:"daily",sc:"抱怨道歉",lv:2},

/* ============ 旅遊英文 · 擴充 ============ */
{id:"t061",en:"We're planning to stay for about a week.",zh:"我們打算待大約一週。",cat:"travel",sc:"行程",lv:2},
{id:"t062",en:"What's the must-see place around here?",zh:"這附近有什麼一定要看的地方？",cat:"travel",sc:"行程",lv:2,note:"must-see = 必看的（當形容詞）"},
{id:"t063",en:"Is it easy to get around without a car?",zh:"沒有車在這裡好移動嗎？",cat:"travel",sc:"行程",lv:3,note:"get around = 四處移動"},
{id:"t064",en:"We're thinking of doing a day trip tomorrow.",zh:"我們在考慮明天來個一日遊。",cat:"travel",sc:"行程",lv:2,note:"think of + Ving"},
{id:"t065",en:"How far is it from the city center?",zh:"離市中心多遠？",cat:"travel",sc:"行程",lv:1},
{id:"t066",en:"Do you know if it's open on Mondays?",zh:"你知道週一有開嗎？",cat:"travel",sc:"行程",lv:2,note:"間接問句：if 後面用直述語序"},
{id:"t067",en:"We'd like to avoid the crowds if we can.",zh:"可以的話我們想避開人潮。",cat:"travel",sc:"行程",lv:3},
{id:"t068",en:"Is the weather usually like this in May?",zh:"五月的天氣通常都這樣嗎？",cat:"travel",sc:"行程",lv:2},

{id:"t069",en:"Sorry, my English isn't very good.",zh:"抱歉，我英文不太好。",cat:"travel",sc:"語言不通",lv:1},
{id:"t070",en:"Could you repeat that more slowly, please?",zh:"可以慢一點再說一次嗎？",cat:"travel",sc:"語言不通",lv:1},
{id:"t071",en:"I understand a little, but not everything.",zh:"我聽懂一點，但不是全部。",cat:"travel",sc:"語言不通",lv:2},
{id:"t072",en:"How do you spell that?",zh:"那個怎麼拼？",cat:"travel",sc:"語言不通",lv:1},
{id:"t073",en:"Is there someone who speaks English here?",zh:"這裡有人會說英文嗎？",cat:"travel",sc:"語言不通",lv:2,note:"關係代名詞 who 修飾 someone"},
{id:"t074",en:"Let me look it up on my phone.",zh:"讓我用手機查一下。",cat:"travel",sc:"語言不通",lv:2,note:"look up = 查詢；代名詞要放中間"},

{id:"t075",en:"Where can I exchange money around here?",zh:"這附近哪裡可以換錢？",cat:"travel",sc:"換匯付款",lv:2},
{id:"t076",en:"What's the exchange rate today?",zh:"今天匯率是多少？",cat:"travel",sc:"換匯付款",lv:2},
{id:"t077",en:"Do you take cash only?",zh:"你們只收現金嗎？",cat:"travel",sc:"換匯付款",lv:1},
{id:"t078",en:"Could I have smaller bills, please?",zh:"可以換小鈔給我嗎？",cat:"travel",sc:"換匯付款",lv:2,note:"bills = 紙鈔（美式）"},
{id:"t079",en:"Is there an ATM nearby?",zh:"附近有提款機嗎？",cat:"travel",sc:"換匯付款",lv:1},
{id:"t080",en:"I think you gave me the wrong change.",zh:"我想你找錯錢了。",cat:"travel",sc:"換匯付款",lv:2,note:"change = 找零"},

{id:"t081",en:"What time can we check in?",zh:"我們幾點可以入住？",cat:"travel",sc:"民宿",lv:1},
{id:"t082",en:"Where should I leave the keys when I check out?",zh:"退房時鑰匙要放哪裡？",cat:"travel",sc:"民宿",lv:2},
{id:"t083",en:"Is there a washing machine we can use?",zh:"有洗衣機可以用嗎？",cat:"travel",sc:"民宿",lv:2},
{id:"t084",en:"How do we get to the apartment from the airport?",zh:"從機場怎麼到公寓？",cat:"travel",sc:"民宿",lv:2},
{id:"t085",en:"The heater doesn't seem to be working.",zh:"暖氣好像壞了。",cat:"travel",sc:"民宿",lv:3,note:"seem to be = 似乎是（婉轉說法）"},
{id:"t086",en:"Thanks, everything was perfect.",zh:"謝謝，一切都很棒。",cat:"travel",sc:"民宿",lv:1},

{id:"t087",en:"What's this dish made of?",zh:"這道菜是什麼做的？",cat:"travel",sc:"當地體驗",lv:2,note:"be made of = 由…製成"},
{id:"t088",en:"Is this spicy?",zh:"這個會辣嗎？",cat:"travel",sc:"當地體驗",lv:1},
{id:"t089",en:"I'd like to try something local.",zh:"我想試試當地的東西。",cat:"travel",sc:"當地體驗",lv:2},
{id:"t090",en:"Could you write down the name for me?",zh:"可以把名字寫下來給我嗎？",cat:"travel",sc:"當地體驗",lv:1},
{id:"t091",en:"Is it customary to tip here?",zh:"這裡習慣給小費嗎？",cat:"travel",sc:"當地體驗",lv:3,note:"customary = 習俗上的、慣例的"},
{id:"t092",en:"How much should I tip?",zh:"小費應該給多少？",cat:"travel",sc:"當地體驗",lv:1},
{id:"t093",en:"We'd like to join the morning tour.",zh:"我們想參加早上的導覽。",cat:"travel",sc:"當地體驗",lv:2},
{id:"t094",en:"Do you have a menu in English?",zh:"有英文菜單嗎？",cat:"travel",sc:"當地體驗",lv:1},

{id:"t095",en:"How long is the hiking trail?",zh:"這條步道多長？",cat:"travel",sc:"戶外",lv:2},
{id:"t096",en:"Is it safe to swim here?",zh:"這裡游泳安全嗎？",cat:"travel",sc:"戶外",lv:1},
{id:"t097",en:"Do we need to book the campsite in advance?",zh:"營地需要先預訂嗎？",cat:"travel",sc:"戶外",lv:2},
{id:"t098",en:"What should I bring for the hike?",zh:"健行要帶什麼？",cat:"travel",sc:"戶外",lv:1},
{id:"t099",en:"Is there cell service up there?",zh:"上面有手機訊號嗎？",cat:"travel",sc:"戶外",lv:2,note:"cell service = 手機收訊"},
{id:"t100",en:"We should head back before it gets dark.",zh:"我們應該在天黑前回去。",cat:"travel",sc:"戶外",lv:2,note:"head back = 往回走"},

{id:"t101",en:"Do you ship internationally?",zh:"你們有寄國外嗎？",cat:"travel",sc:"寄送",lv:2},
{id:"t102",en:"How long will shipping take?",zh:"運送要多久？",cat:"travel",sc:"寄送",lv:1},
{id:"t103",en:"This is fragile. Could you wrap it well?",zh:"這個易碎，可以包好一點嗎？",cat:"travel",sc:"寄送",lv:2,note:"fragile = 易碎的"},
{id:"t104",en:"I'll take two of these, please.",zh:"這個我要兩個。",cat:"travel",sc:"寄送",lv:1},
{id:"t105",en:"Do you have a bigger bag?",zh:"有大一點的袋子嗎？",cat:"travel",sc:"寄送",lv:1},

{id:"t106",en:"I need to confirm my return flight.",zh:"我需要確認回程班機。",cat:"travel",sc:"回程",lv:2},
{id:"t107",en:"What time should I get to the airport?",zh:"我應該幾點到機場？",cat:"travel",sc:"回程",lv:1},
{id:"t108",en:"Could you call a taxi for me at six?",zh:"可以幫我六點叫台計程車嗎？",cat:"travel",sc:"回程",lv:2},
{id:"t109",en:"Thank you for everything. We had a wonderful time.",zh:"謝謝你的一切，我們玩得很愉快。",cat:"travel",sc:"回程",lv:2},
{id:"t110",en:"I hope to come back someday.",zh:"希望有天能再來。",cat:"travel",sc:"回程",lv:1},

/* ============ 單字強化（填空專用，句子日常但單字有難度） ============ */
{id:"v001",en:"The instructions were surprisingly straightforward.",zh:"說明出乎意料地簡單明瞭。",cat:"vocab",sc:"形容事物",lv:3,bl:["straightforward"],note:"straightforward＝直截了當、不繞彎"},
{id:"v002",en:"She handled the complaint very professionally.",zh:"她非常專業地處理了那個客訴。",cat:"vocab",sc:"形容人",lv:3,bl:["professionally"],note:"handle＝處理；complaint＝客訴"},
{id:"v003",en:"I'm not entirely convinced by his explanation.",zh:"我不完全被他的解釋說服。",cat:"vocab",sc:"表達意見",lv:3,bl:["convinced"],note:"be convinced by＝被…說服"},
{id:"v004",en:"The deadline is flexible, so don't panic.",zh:"期限有彈性，別慌。",cat:"vocab",sc:"工作",lv:2,bl:["flexible"],note:"flexible＝有彈性的"},
{id:"v005",en:"That restaurant is ridiculously expensive.",zh:"那間餐廳貴得離譜。",cat:"vocab",sc:"形容事物",lv:3,bl:["ridiculously"],note:"ridiculously＝誇張到荒謬的程度"},
{id:"v006",en:"We need to prioritize the urgent tasks first.",zh:"我們需要先處理最急的事。",cat:"vocab",sc:"工作",lv:3,bl:["prioritize"],note:"prioritize＝排優先順序"},
{id:"v007",en:"His attitude has improved significantly.",zh:"他的態度明顯改善了。",cat:"vocab",sc:"形容人",lv:3,bl:["significantly"],note:"significantly＝顯著地"},
{id:"v008",en:"I'd appreciate it if you could be more specific.",zh:"你可以講具體一點我會很感謝。",cat:"vocab",sc:"表達意見",lv:3,bl:["specific"],note:"specific＝具體的、明確的"},
{id:"v009",en:"The results were disappointing, to be honest.",zh:"老實說結果令人失望。",cat:"vocab",sc:"表達意見",lv:2,bl:["disappointing"],note:"disappointing＝令人失望的（形容事）"},
{id:"v010",en:"She's incredibly patient with beginners.",zh:"她對初學者非常有耐心。",cat:"vocab",sc:"形容人",lv:3,bl:["incredibly","patient"],note:"be patient with＝對…有耐心"},
{id:"v011",en:"This route is more convenient than the other one.",zh:"這條路比另一條方便。",cat:"vocab",sc:"形容事物",lv:2,bl:["convenient"],note:"convenient＝方便的（形容事物，不形容人）"},
{id:"v012",en:"I completely underestimated how long it would take.",zh:"我完全低估了這要花多久。",cat:"vocab",sc:"表達意見",lv:3,bl:["underestimated"],note:"underestimate＝低估（反義 overestimate）"},
{id:"v013",en:"The service was efficient and friendly.",zh:"服務又有效率又親切。",cat:"vocab",sc:"形容事物",lv:2,bl:["efficient"],note:"efficient＝有效率的"},
{id:"v014",en:"It's essential to book ahead during holidays.",zh:"假期期間務必提前訂位。",cat:"vocab",sc:"旅遊",lv:3,bl:["essential"],note:"essential＝不可或缺的、務必的"},
{id:"v015",en:"He gave a fairly reasonable excuse.",zh:"他給了一個還算合理的理由。",cat:"vocab",sc:"形容人",lv:3,bl:["reasonable"],note:"fairly＝還算；reasonable＝合理的"},
{id:"v016",en:"I find the whole situation quite frustrating.",zh:"我覺得整件事相當令人洩氣。",cat:"vocab",sc:"情緒",lv:3,bl:["frustrating"],note:"frustrating 形容事，frustrated 形容人"},
{id:"v017",en:"They're reluctant to change their policy.",zh:"他們不太願意改變政策。",cat:"vocab",sc:"工作",lv:3,bl:["reluctant"],note:"be reluctant to＝不情願做…"},
{id:"v018",en:"Her presentation was clear and persuasive.",zh:"她的簡報清楚又有說服力。",cat:"vocab",sc:"工作",lv:3,bl:["persuasive"],note:"persuasive＝有說服力的"},
{id:"v019",en:"We should consider the long-term consequences.",zh:"我們該考慮長期後果。",cat:"vocab",sc:"表達意見",lv:3,bl:["consequences"],note:"consequence＝後果（多為負面）"},
{id:"v020",en:"That's a reasonable compromise for both sides.",zh:"那對雙方都是合理的折衷。",cat:"vocab",sc:"表達意見",lv:3,bl:["compromise"],note:"compromise＝妥協、折衷方案"},
{id:"v021",en:"I'm genuinely curious about how it works.",zh:"我真的很好奇它怎麼運作。",cat:"vocab",sc:"情緒",lv:3,bl:["genuinely","curious"],note:"be curious about＝對…好奇"},
{id:"v022",en:"The instructions were vague and confusing.",zh:"說明模糊又令人困惑。",cat:"vocab",sc:"形容事物",lv:3,bl:["vague"],note:"vague＝含糊不清的"},
{id:"v023",en:"He tends to exaggerate a little.",zh:"他有點愛誇大。",cat:"vocab",sc:"形容人",lv:3,bl:["exaggerate"],note:"tend to＝傾向；exaggerate＝誇大"},
{id:"v024",en:"I'd rather be honest than diplomatic.",zh:"我寧願誠實也不要圓滑。",cat:"vocab",sc:"表達意見",lv:3,bl:["diplomatic"],note:"diplomatic＝圓滑的、講話得體的"},
{id:"v025",en:"The food was decent but nothing special.",zh:"食物還可以但沒什麼特別。",cat:"vocab",sc:"形容事物",lv:2,bl:["decent"],note:"decent＝還不錯、及格的"},
{id:"v026",en:"She's remarkably calm under pressure.",zh:"她在壓力下出奇地冷靜。",cat:"vocab",sc:"形容人",lv:3,bl:["remarkably"],note:"under pressure＝在壓力下"},
{id:"v027",en:"We're gradually getting used to the new system.",zh:"我們正逐漸習慣新系統。",cat:"vocab",sc:"工作",lv:3,bl:["gradually"],note:"get used to + Ving/名詞＝逐漸習慣"},
{id:"v028",en:"That assumption turned out to be wrong.",zh:"那個假設結果是錯的。",cat:"vocab",sc:"表達意見",lv:3,bl:["assumption"],note:"turn out to be＝結果證明是"},
{id:"v029",en:"His comment was unnecessarily harsh.",zh:"他的評論嚴厲得沒必要。",cat:"vocab",sc:"形容人",lv:3,bl:["unnecessarily","harsh"],note:"harsh＝嚴厲的、刺耳的"},
{id:"v030",en:"The process is fairly complicated at first.",zh:"這流程一開始相當複雜。",cat:"vocab",sc:"形容事物",lv:2,bl:["complicated"],note:"complicated＝複雜的"},
{id:"v031",en:"I'm hesitant to make a decision right now.",zh:"我現在猶豫要不要做決定。",cat:"vocab",sc:"情緒",lv:3,bl:["hesitant"],note:"be hesitant to＝猶豫要不要"},
{id:"v032",en:"Their response was surprisingly generous.",zh:"他們的回應出乎意料地大方。",cat:"vocab",sc:"形容人",lv:3,bl:["generous"],note:"generous＝慷慨的、大方的"},
{id:"v033",en:"It's crucial that we arrive on time.",zh:"我們準時抵達至關重要。",cat:"vocab",sc:"工作",lv:3,bl:["crucial"],note:"crucial＝關鍵的（比 important 更強）"},
{id:"v034",en:"She's extremely reliable when it matters.",zh:"關鍵時刻她非常可靠。",cat:"vocab",sc:"形容人",lv:3,bl:["reliable"],note:"reliable＝可靠的、靠得住的"},
{id:"v035",en:"I was overwhelmed by all the options.",zh:"那麼多選擇讓我不知所措。",cat:"vocab",sc:"情緒",lv:3,bl:["overwhelmed"],note:"be overwhelmed by＝被…淹沒、招架不住"},
{id:"v036",en:"He apologized sincerely for the delay.",zh:"他為延誤誠懇地道歉。",cat:"vocab",sc:"抱怨道歉",lv:3,bl:["sincerely"],note:"apologize for＝為…道歉"},
{id:"v037",en:"The atmosphere in that café is really cozy.",zh:"那間咖啡廳氣氛很溫馨。",cat:"vocab",sc:"形容事物",lv:3,bl:["atmosphere","cozy"],note:"cozy＝溫馨舒適的"},
{id:"v038",en:"We're aiming to finish by the end of the month.",zh:"我們目標是月底前完成。",cat:"vocab",sc:"工作",lv:3,bl:["aiming"],note:"aim to + 原形＝以…為目標"},
{id:"v039",en:"That's an interesting perspective.",zh:"那是個有趣的觀點。",cat:"vocab",sc:"表達意見",lv:2,bl:["perspective"],note:"perspective＝觀點、角度"},
{id:"v040",en:"I'm gradually becoming more confident.",zh:"我正逐漸變得更有自信。",cat:"vocab",sc:"情緒",lv:2,bl:["confident"],note:"confident＝有自信的"},
{id:"v041",en:"The policy is subject to change.",zh:"政策可能會有變動。",cat:"vocab",sc:"工作",lv:3,bl:["subject"],note:"be subject to change＝可能會變動（公告常用）"},
{id:"v042",en:"She's very considerate of other people.",zh:"她很為別人著想。",cat:"vocab",sc:"形容人",lv:3,bl:["considerate"],note:"considerate＝體貼的（別跟 considerable 搞混）"},
{id:"v043",en:"It's a temporary solution, not a permanent one.",zh:"這是暫時的辦法，不是永久的。",cat:"vocab",sc:"形容事物",lv:3,bl:["temporary","permanent"],note:"temporary 暫時／permanent 永久"},
{id:"v044",en:"I found his argument fairly convincing.",zh:"我覺得他的論點還算有說服力。",cat:"vocab",sc:"表達意見",lv:3,bl:["convincing"],note:"convincing 形容事物，convinced 形容人"},
{id:"v045",en:"We had to make a few adjustments.",zh:"我們必須做一些調整。",cat:"vocab",sc:"工作",lv:2,bl:["adjustments"],note:"make adjustments＝做調整"},
{id:"v046",en:"The neighborhood is quiet and residential.",zh:"那一區安靜，是住宅區。",cat:"vocab",sc:"旅遊",lv:3,bl:["neighborhood","residential"],note:"neighborhood＝社區、一帶"},
{id:"v047",en:"That's a common misconception.",zh:"那是個常見的誤解。",cat:"vocab",sc:"表達意見",lv:3,bl:["misconception"],note:"mis-（錯）+ conception（概念）"},
{id:"v048",en:"He responded almost immediately.",zh:"他幾乎立刻就回覆了。",cat:"vocab",sc:"工作",lv:2,bl:["immediately"],note:"immediately＝立刻"},
{id:"v049",en:"I'm slightly concerned about the cost.",zh:"我有點擔心費用。",cat:"vocab",sc:"情緒",lv:3,bl:["slightly","concerned"],note:"be concerned about＝擔心"},
{id:"v050",en:"The quality is consistent across all their stores.",zh:"他們所有分店品質都很一致。",cat:"vocab",sc:"形容事物",lv:3,bl:["consistent"],note:"consistent＝一致的、穩定的"},
{id:"v051",en:"It's worth mentioning that prices vary.",zh:"值得一提的是價格會有差異。",cat:"vocab",sc:"表達意見",lv:3,bl:["mentioning","vary"],note:"be worth + Ving；vary＝有所不同"},
{id:"v052",en:"She's fluent in three languages.",zh:"她三種語言都很流利。",cat:"vocab",sc:"形容人",lv:2,bl:["fluent"],note:"be fluent in + 語言"},
{id:"v053",en:"That approach seems more practical.",zh:"那個做法看起來比較實際。",cat:"vocab",sc:"表達意見",lv:3,bl:["approach","practical"],note:"approach＝做法、途徑"},
{id:"v054",en:"I'd describe the taste as mild.",zh:"我會形容那個味道是清淡的。",cat:"vocab",sc:"形容事物",lv:3,bl:["describe","mild"],note:"describe A as B＝把 A 形容成 B"},
{id:"v055",en:"They were incredibly accommodating.",zh:"他們非常好商量、很配合。",cat:"vocab",sc:"形容人",lv:3,bl:["accommodating"],note:"accommodating＝樂於配合的"},
{id:"v056",en:"The seats were surprisingly comfortable.",zh:"座位出乎意料地舒服。",cat:"vocab",sc:"旅遊",lv:2,bl:["comfortable"],note:"comfortable 唸三音節 KUMF-ter-bul"},
{id:"v057",en:"It's a matter of personal preference.",zh:"這是個人喜好的問題。",cat:"vocab",sc:"表達意見",lv:3,bl:["preference"],note:"a matter of＝…的問題"},
{id:"v058",en:"We should double-check the details beforehand.",zh:"我們應該事先再確認細節。",cat:"vocab",sc:"工作",lv:3,bl:["beforehand"],note:"beforehand＝事先（放句尾）"},
{id:"v059",en:"The instructions clearly state otherwise.",zh:"說明清楚寫的不是這樣。",cat:"vocab",sc:"工作",lv:3,bl:["otherwise"],note:"state otherwise＝寫的／說的相反"},
{id:"v060",en:"I'm fairly familiar with that area.",zh:"我對那一帶還算熟。",cat:"vocab",sc:"旅遊",lv:2,bl:["familiar"],note:"be familiar with＝對…熟悉"},
{id:"v061",en:"That was an unexpected but welcome surprise.",zh:"那是意外但令人開心的驚喜。",cat:"vocab",sc:"情緒",lv:3,bl:["unexpected"],note:"welcome 當形容詞＝令人欣喜的"},
{id:"v062",en:"Their prices are relatively affordable.",zh:"他們價格相對實惠。",cat:"vocab",sc:"金錢",lv:3,bl:["relatively","affordable"],note:"affordable＝負擔得起的"},
{id:"v063",en:"I'd prefer a more casual atmosphere.",zh:"我比較喜歡輕鬆一點的氣氛。",cat:"vocab",sc:"社交",lv:2,bl:["casual"],note:"casual＝隨性的、不正式的"},
{id:"v064",en:"It requires a fair amount of patience.",zh:"這需要相當的耐心。",cat:"vocab",sc:"形容事物",lv:3,bl:["requires","patience"],note:"a fair amount of＝相當多的"},
{id:"v065",en:"The difference is barely noticeable.",zh:"差別幾乎看不出來。",cat:"vocab",sc:"形容事物",lv:3,bl:["barely","noticeable"],note:"barely＝幾乎不（本身帶否定）"},
{id:"v066",en:"We managed to resolve it eventually.",zh:"我們最後設法解決了。",cat:"vocab",sc:"工作",lv:3,bl:["resolve","eventually"],note:"manage to＝設法做到；eventually＝最終"},
{id:"v067",en:"That's an unfortunate misunderstanding.",zh:"那是個不幸的誤會。",cat:"vocab",sc:"抱怨道歉",lv:3,bl:["unfortunate","misunderstanding"],note:"unfortunate＝令人遺憾的"},
{id:"v068",en:"The instructions were poorly translated.",zh:"說明翻譯得很差。",cat:"vocab",sc:"形容事物",lv:3,bl:["poorly","translated"],note:"poorly + 過去分詞＝做得很差"},
{id:"v069",en:"It's inconvenient, but not impossible.",zh:"這不方便，但不是不可能。",cat:"vocab",sc:"表達意見",lv:3,bl:["inconvenient"],note:"in- 前綴表否定"},
{id:"v070",en:"They handled the situation appropriately.",zh:"他們妥善地處理了那個狀況。",cat:"vocab",sc:"工作",lv:3,bl:["appropriately"],note:"appropriate＝適當的"},
{id:"v071",en:"I'm reasonably satisfied with the result.",zh:"我對結果還算滿意。",cat:"vocab",sc:"情緒",lv:3,bl:["reasonably","satisfied"],note:"be satisfied with＝對…滿意"},
{id:"v072",en:"The event was surprisingly well organized.",zh:"活動辦得出乎意料地好。",cat:"vocab",sc:"形容事物",lv:3,bl:["organized"],note:"well organized＝組織得好"},
{id:"v073",en:"He seemed distracted during the meeting.",zh:"他開會時看起來心不在焉。",cat:"vocab",sc:"形容人",lv:3,bl:["distracted"],note:"distracted＝分心的"},
{id:"v074",en:"That's a significant improvement.",zh:"那是明顯的進步。",cat:"vocab",sc:"表達意見",lv:2,bl:["significant","improvement"],note:"significant＝顯著的"},
{id:"v075",en:"We need to clarify a few points.",zh:"我們需要釐清幾個點。",cat:"vocab",sc:"工作",lv:3,bl:["clarify"],note:"clarify＝澄清、釐清"},
{id:"v076",en:"Their staff were exceptionally helpful.",zh:"他們的員工幫忙得無可挑剔。",cat:"vocab",sc:"形容人",lv:3,bl:["exceptionally"],note:"exceptionally＝格外地、非常地"},
{id:"v077",en:"The instructions were deliberately vague.",zh:"說明是故意寫得模糊。",cat:"vocab",sc:"形容事物",lv:3,bl:["deliberately"],note:"deliberately＝刻意地"},
{id:"v078",en:"She's capable of handling it alone.",zh:"她有能力自己處理。",cat:"vocab",sc:"形容人",lv:3,bl:["capable"],note:"be capable of + Ving＝有能力做"},
{id:"v079",en:"That's absolutely worth considering.",zh:"那絕對值得考慮。",cat:"vocab",sc:"表達意見",lv:3,bl:["absolutely","considering"],note:"worth + Ving"},
{id:"v080",en:"I'd rather not commit to anything yet.",zh:"我還不想先答應任何事。",cat:"vocab",sc:"表達意見",lv:3,bl:["commit"],note:"commit to＝承諾、投入"}

]);
