/* Echo 英語 — 擴充句庫 5（250 句，湊滿 1000 句）
   欄位說明同 bank.js／bank2.js
*/
window.BANK = (window.BANK||[]).concat([

/* ============ 日常會話 · 看電影追劇 ============ */
{id:"d361",en:"Have you seen anything good lately?",zh:"你最近有看到什麼好看的嗎？",cat:"daily",sc:"看電影追劇",lv:1},
{id:"d362",en:"No spoilers, please! I haven't finished it yet.",zh:"拜託不要爆雷！我還沒看完。",cat:"daily",sc:"看電影追劇",lv:1,note:"spoiler = 爆雷、劇透"},
{id:"d363",en:"I binge-watched the whole season in one weekend.",zh:"我一個週末就把整季追完了。",cat:"daily",sc:"看電影追劇",lv:2,note:"binge-watch = 一口氣狂看"},
{id:"d364",en:"The ending totally caught me off guard.",zh:"那個結局完全出乎我意料。",cat:"daily",sc:"看電影追劇",lv:2,note:"catch someone off guard = 讓人措手不及"},
{id:"d365",en:"Do you want to see a movie this weekend?",zh:"這週末要不要去看電影？",cat:"daily",sc:"看電影追劇",lv:1},
{id:"d366",en:"The book was way better than the movie.",zh:"原著比電影好看太多了。",cat:"daily",sc:"看電影追劇",lv:1},
{id:"d367",en:"I fell asleep halfway through it.",zh:"我看到一半就睡著了。",cat:"daily",sc:"看電影追劇",lv:1},
{id:"d368",en:"It's a slow burn, but it's worth sticking with.",zh:"它節奏比較慢，但值得看下去。",cat:"daily",sc:"看電影追劇",lv:3,note:"slow burn = 慢熱；stick with = 堅持下去"},
{id:"d369",en:"Should we turn on the subtitles?",zh:"我們要不要開字幕？",cat:"daily",sc:"看電影追劇",lv:1},
{id:"d370",en:"I can't believe they canceled the show after one season.",zh:"真不敢相信他們只播一季就把這部劇砍了。",cat:"daily",sc:"看電影追劇",lv:2},

/* ============ 日常會話 · 搬家租屋 ============ */
{id:"d371",en:"I'm looking for a place closer to work.",zh:"我在找離公司近一點的房子。",cat:"daily",sc:"搬家租屋",lv:1},
{id:"d372",en:"How much is the rent, including utilities?",zh:"房租含水電費是多少？",cat:"daily",sc:"搬家租屋",lv:2,note:"utilities = 水電瓦斯等費用"},
{id:"d373",en:"Is the deposit refundable when I move out?",zh:"我搬走的時候押金可以退嗎？",cat:"daily",sc:"搬家租屋",lv:2,note:"refundable = 可退還的"},
{id:"d374",en:"The landlord still hasn't fixed the leaky faucet.",zh:"房東到現在還沒修好漏水的水龍頭。",cat:"daily",sc:"搬家租屋",lv:2,note:"leaky = 會漏水的"},
{id:"d375",en:"We're moving next Saturday, can you help?",zh:"我們下週六搬家，你可以來幫忙嗎？",cat:"daily",sc:"搬家租屋",lv:1},
{id:"d376",en:"I've been packing boxes all week.",zh:"我整個禮拜都在打包箱子。",cat:"daily",sc:"搬家租屋",lv:1},
{id:"d377",en:"Are pets allowed in this building?",zh:"這棟大樓可以養寵物嗎？",cat:"daily",sc:"搬家租屋",lv:1},
{id:"d378",en:"I'd like to sign a one-year lease.",zh:"我想簽一年的租約。",cat:"daily",sc:"搬家租屋",lv:2,note:"lease = 租約"},
{id:"d379",en:"The apartment gets a lot of natural light.",zh:"這間公寓採光很好。",cat:"daily",sc:"搬家租屋",lv:2},
{id:"d380",en:"It's a bit out of my price range.",zh:"這有點超出我的預算。",cat:"daily",sc:"搬家租屋",lv:2,note:"price range = 價格範圍"},

/* ============ 日常會話 · 美容美髮 ============ */
{id:"d381",en:"I'd like to get a haircut, just a trim.",zh:"我想剪頭髮，稍微修一下就好。",cat:"daily",sc:"美容美髮",lv:1,note:"trim = 修剪"},
{id:"d382",en:"Could you take a little more off the sides?",zh:"兩邊可以再剪短一點嗎？",cat:"daily",sc:"美容美髮",lv:2},
{id:"d383",en:"Not too short, please.",zh:"請不要剪太短。",cat:"daily",sc:"美容美髮",lv:1},
{id:"d384",en:"I'm thinking about dyeing my hair brown.",zh:"我在考慮把頭髮染成咖啡色。",cat:"daily",sc:"美容美髮",lv:2},
{id:"d385",en:"Do I need to book an appointment?",zh:"需要先預約嗎？",cat:"daily",sc:"美容美髮",lv:1},
{id:"d386",en:"Something low-maintenance would be great.",zh:"好整理一點的髮型最好。",cat:"daily",sc:"美容美髮",lv:3,note:"low-maintenance = 不費心打理的"},
{id:"d387",en:"Can you show me how to style it at home?",zh:"可以教我回家怎麼整理嗎？",cat:"daily",sc:"美容美髮",lv:2},
{id:"d388",en:"My hair gets frizzy when it's humid.",zh:"天氣潮濕的時候我的頭髮會很毛躁。",cat:"daily",sc:"美容美髮",lv:3,note:"frizzy = 毛躁的"},
{id:"d389",en:"I love it, it looks so much better.",zh:"我很喜歡，看起來好多了。",cat:"daily",sc:"美容美髮",lv:1},
{id:"d390",en:"You got a haircut! It really suits you.",zh:"你剪頭髮了！很適合你。",cat:"daily",sc:"美容美髮",lv:1,note:"suit someone = 適合某人"},

/* ============ 日常會話 · 修車保養 ============ */
{id:"d391",en:"My car's making a weird noise when I brake.",zh:"我的車踩煞車的時候有怪聲。",cat:"daily",sc:"修車保養",lv:2},
{id:"d392",en:"It's time for an oil change.",zh:"該換機油了。",cat:"daily",sc:"修車保養",lv:1},
{id:"d393",en:"The check engine light just came on.",zh:"引擎警示燈剛剛亮了。",cat:"daily",sc:"修車保養",lv:2},
{id:"d394",en:"I think I've got a flat tire.",zh:"我覺得我爆胎了。",cat:"daily",sc:"修車保養",lv:1,note:"flat tire = 爆胎、沒氣的輪胎"},
{id:"d395",en:"How long will the repair take?",zh:"修理要多久？",cat:"daily",sc:"修車保養",lv:1},
{id:"d396",en:"Can you give me a rough estimate first?",zh:"可以先給我一個大概的估價嗎？",cat:"daily",sc:"修車保養",lv:2,note:"rough estimate = 粗估"},
{id:"d397",en:"The battery died, so I need a jump start.",zh:"電瓶沒電了，我需要接電發動。",cat:"daily",sc:"修車保養",lv:3,note:"jump start = 借電發動"},
{id:"d398",en:"Is it still covered under warranty?",zh:"這還在保固範圍內嗎？",cat:"daily",sc:"修車保養",lv:2,note:"warranty = 保固"},
{id:"d399",en:"I'll leave the car here and pick it up tomorrow.",zh:"我把車留在這裡，明天再來牽。",cat:"daily",sc:"修車保養",lv:2},
{id:"d400",en:"The air conditioning isn't blowing cold air.",zh:"冷氣吹不出冷風。",cat:"daily",sc:"修車保養",lv:2},

/* ============ 日常會話 · 下廚料理 ============ */
{id:"d401",en:"What should we make for dinner tonight?",zh:"我們今晚晚餐要煮什麼？",cat:"daily",sc:"下廚料理",lv:1},
{id:"d402",en:"Could you chop the onions for me?",zh:"可以幫我切洋蔥嗎？",cat:"daily",sc:"下廚料理",lv:1},
{id:"d403",en:"Let it simmer for about twenty minutes.",zh:"用小火燉大約二十分鐘。",cat:"daily",sc:"下廚料理",lv:2,note:"simmer = 小火慢燉"},
{id:"d404",en:"I think I added too much salt.",zh:"我覺得我鹽加太多了。",cat:"daily",sc:"下廚料理",lv:1},
{id:"d405",en:"This recipe is easier than it looks.",zh:"這道食譜比看起來簡單。",cat:"daily",sc:"下廚料理",lv:1},
{id:"d406",en:"Preheat the oven to two hundred degrees.",zh:"烤箱先預熱到兩百度。",cat:"daily",sc:"下廚料理",lv:2,note:"preheat = 預熱"},
{id:"d407",en:"We're out of eggs, can you grab some on your way home?",zh:"蛋用完了，你回家路上可以順便買嗎？",cat:"daily",sc:"下廚料理",lv:2,note:"be out of = 用完了"},
{id:"d408",en:"It smells amazing in here.",zh:"這裡聞起來好香。",cat:"daily",sc:"下廚料理",lv:1},
{id:"d409",en:"I usually cook a big batch on Sunday for the whole week.",zh:"我通常週日煮一大鍋，吃一整個禮拜。",cat:"daily",sc:"下廚料理",lv:3,note:"batch = 一批"},
{id:"d410",en:"Taste it and tell me if it needs anything.",zh:"嚐嚐看，跟我說還需不需要加什麼。",cat:"daily",sc:"下廚料理",lv:2},

/* ============ 日常會話 · 約會戀愛 ============ */
{id:"d411",en:"Would you like to grab a coffee sometime?",zh:"改天要不要一起喝杯咖啡？",cat:"daily",sc:"約會戀愛",lv:1},
{id:"d412",en:"I had a really great time tonight.",zh:"我今晚過得很開心。",cat:"daily",sc:"約會戀愛",lv:1},
{id:"d413",en:"How did you two meet?",zh:"你們兩個是怎麼認識的？",cat:"daily",sc:"約會戀愛",lv:1},
{id:"d414",en:"We hit it off right away.",zh:"我們一見面就很合得來。",cat:"daily",sc:"約會戀愛",lv:2,note:"hit it off = 一拍即合"},
{id:"d415",en:"I think I'm falling for him.",zh:"我覺得我愛上他了。",cat:"daily",sc:"約會戀愛",lv:2,note:"fall for someone = 愛上某人"},
{id:"d416",en:"We've been together for three years now.",zh:"我們在一起三年了。",cat:"daily",sc:"約會戀愛",lv:1},
{id:"d417",en:"She's been on my mind all day.",zh:"我一整天都在想她。",cat:"daily",sc:"約會戀愛",lv:2,note:"on one's mind = 掛念著"},
{id:"d418",en:"We decided to take things slow.",zh:"我們決定慢慢來。",cat:"daily",sc:"約會戀愛",lv:2},
{id:"d419",en:"Long-distance relationships are really hard to maintain.",zh:"遠距離戀愛真的很難維持。",cat:"daily",sc:"約會戀愛",lv:3},
{id:"d420",en:"Happy anniversary! I made a reservation at your favorite place.",zh:"紀念日快樂！我訂了你最喜歡的那家店。",cat:"daily",sc:"約會戀愛",lv:2},

/* ============ 日常會話 · 面試求職 ============ */
{id:"d421",en:"Could you tell me a little about yourself?",zh:"可以簡單介紹一下你自己嗎？",cat:"daily",sc:"面試求職",lv:1},
{id:"d422",en:"I have five years of experience in marketing.",zh:"我有五年的行銷經驗。",cat:"daily",sc:"面試求職",lv:1},
{id:"d423",en:"Why are you interested in this position?",zh:"你為什麼對這個職位有興趣？",cat:"daily",sc:"面試求職",lv:2},
{id:"d424",en:"My biggest strength is that I learn quickly.",zh:"我最大的優點是學東西很快。",cat:"daily",sc:"面試求職",lv:2},
{id:"d425",en:"I'm looking for a role where I can grow.",zh:"我在找一個能讓我成長的職位。",cat:"daily",sc:"面試求職",lv:2},
{id:"d426",en:"I led a team of six on that project.",zh:"那個專案我帶了一個六人團隊。",cat:"daily",sc:"面試求職",lv:2},
{id:"d427",en:"What does a typical day look like in this role?",zh:"這個職位平常一天的工作大概是怎樣？",cat:"daily",sc:"面試求職",lv:2},
{id:"d428",en:"I'm open to discussing the salary.",zh:"薪水的部分我願意再討論。",cat:"daily",sc:"面試求職",lv:2},
{id:"d429",en:"When can I expect to hear back from you?",zh:"我大概什麼時候會收到你們的回覆？",cat:"daily",sc:"面試求職",lv:2,note:"hear back = 得到回音"},
{id:"d430",en:"Thank you for taking the time to meet with me.",zh:"謝謝你撥空跟我面談。",cat:"daily",sc:"面試求職",lv:1},

/* ============ 日常會話 · 開會簡報 ============ */
{id:"d431",en:"Let's get started, since everyone's here.",zh:"大家都到了，我們開始吧。",cat:"daily",sc:"開會簡報",lv:1},
{id:"d432",en:"Could you share your screen?",zh:"你可以分享一下螢幕嗎？",cat:"daily",sc:"開會簡報",lv:1},
{id:"d433",en:"Sorry, you're on mute.",zh:"不好意思，你開靜音了。",cat:"daily",sc:"開會簡報",lv:1},
{id:"d434",en:"Let's move on to the next item on the agenda.",zh:"我們進到議程的下一項。",cat:"daily",sc:"開會簡報",lv:2,note:"agenda = 議程"},
{id:"d435",en:"I'll keep this brief.",zh:"我長話短說。",cat:"daily",sc:"開會簡報",lv:2},
{id:"d436",en:"As you can see from this chart, sales went up last quarter.",zh:"從這張圖可以看到，上一季的業績成長了。",cat:"daily",sc:"開會簡報",lv:3,note:"quarter = 一季"},
{id:"d437",en:"Can we circle back to that later?",zh:"那個我們可以晚點再回來討論嗎？",cat:"daily",sc:"開會簡報",lv:3,note:"circle back = 稍後再回頭談"},
{id:"d438",en:"Does anyone have any questions so far?",zh:"到目前為止大家有問題嗎？",cat:"daily",sc:"開會簡報",lv:1},
{id:"d439",en:"Let's take this offline.",zh:"這個我們會後再私下討論。",cat:"daily",sc:"開會簡報",lv:3,note:"take it offline = 會後另外談"},
{id:"d440",en:"I'll send out the meeting notes this afternoon.",zh:"我今天下午會把會議紀錄寄出去。",cat:"daily",sc:"開會簡報",lv:2},

/* ============ 日常會話 · 銀行郵局 ============ */
{id:"d441",en:"I'd like to open a savings account.",zh:"我想開一個儲蓄帳戶。",cat:"daily",sc:"銀行郵局",lv:1},
{id:"d442",en:"I need to transfer some money overseas.",zh:"我需要匯一些錢到國外。",cat:"daily",sc:"銀行郵局",lv:2},
{id:"d443",en:"How much is the fee for an international transfer?",zh:"國際匯款的手續費是多少？",cat:"daily",sc:"銀行郵局",lv:2},
{id:"d444",en:"My card got stuck in the ATM.",zh:"我的卡被提款機吃掉了。",cat:"daily",sc:"銀行郵局",lv:2},
{id:"d445",en:"I think there's an error on my statement.",zh:"我覺得我的對帳單有錯。",cat:"daily",sc:"銀行郵局",lv:2,note:"statement = 對帳單"},
{id:"d446",en:"I'd like to send this package by registered mail.",zh:"我想用掛號寄這個包裹。",cat:"daily",sc:"銀行郵局",lv:2,note:"registered mail = 掛號信"},
{id:"d447",en:"How long will it take to arrive?",zh:"大概多久會寄到？",cat:"daily",sc:"銀行郵局",lv:1},
{id:"d448",en:"I'd like to report a lost credit card.",zh:"我要掛失信用卡。",cat:"daily",sc:"銀行郵局",lv:2},
{id:"d449",en:"Do I need to bring my ID?",zh:"我需要帶身分證嗎？",cat:"daily",sc:"銀行郵局",lv:1},
{id:"d450",en:"Can I pick up a package for someone else?",zh:"我可以幫別人領包裹嗎？",cat:"daily",sc:"銀行郵局",lv:2},

/* ============ 日常會話 · 生病請假 ============ */
{id:"d451",en:"I'm not feeling well, so I'm going to stay home today.",zh:"我身體不太舒服，今天要在家休息。",cat:"daily",sc:"生病請假",lv:1},
{id:"d452",en:"I think I'm coming down with a cold.",zh:"我覺得我快感冒了。",cat:"daily",sc:"生病請假",lv:2,note:"come down with = 染上（小病）"},
{id:"d453",en:"I've had a fever since last night.",zh:"我從昨晚就開始發燒。",cat:"daily",sc:"生病請假",lv:1},
{id:"d454",en:"I'd like to take a sick day tomorrow.",zh:"我明天想請一天病假。",cat:"daily",sc:"生病請假",lv:2,note:"sick day = 病假"},
{id:"d455",en:"I'll be checking my email if anything urgent comes up.",zh:"如果有急事，我還是會看信箱。",cat:"daily",sc:"生病請假",lv:2},
{id:"d456",en:"My throat is killing me.",zh:"我的喉嚨痛死了。",cat:"daily",sc:"生病請假",lv:2,note:"... is killing me = 某處痛得要命"},
{id:"d457",en:"Get some rest and drink plenty of water.",zh:"好好休息，多喝水。",cat:"daily",sc:"生病請假",lv:1},
{id:"d458",en:"I don't want to spread it to everyone at the office.",zh:"我不想傳染給辦公室的大家。",cat:"daily",sc:"生病請假",lv:2},
{id:"d459",en:"I'm feeling a lot better today, thanks.",zh:"我今天好多了，謝謝。",cat:"daily",sc:"生病請假",lv:1},
{id:"d460",en:"Hope you feel better soon!",zh:"希望你早日康復！",cat:"daily",sc:"生病請假",lv:1},

/* ============ 日常會話 · 鄰居社區 ============ */
{id:"d461",en:"Hi, I just moved in next door.",zh:"嗨，我剛搬到你隔壁。",cat:"daily",sc:"鄰居社區",lv:1},
{id:"d462",en:"Let me know if you ever need anything.",zh:"如果你需要什麼儘管跟我說。",cat:"daily",sc:"鄰居社區",lv:1},
{id:"d463",en:"Could you keep the noise down a little at night?",zh:"晚上可以稍微小聲一點嗎？",cat:"daily",sc:"鄰居社區",lv:2,note:"keep the noise down = 降低音量"},
{id:"d464",en:"I think this package was delivered to me by mistake.",zh:"這個包裹好像被誤送到我這裡了。",cat:"daily",sc:"鄰居社區",lv:2},
{id:"d465",en:"Would you mind watering my plants while I'm away?",zh:"我不在的時候可以幫我澆花嗎？",cat:"daily",sc:"鄰居社區",lv:2},
{id:"d466",en:"Which day is recycling collected here?",zh:"這裡哪一天收資源回收？",cat:"daily",sc:"鄰居社區",lv:2},
{id:"d467",en:"The elevator is out of order again.",zh:"電梯又故障了。",cat:"daily",sc:"鄰居社區",lv:2,note:"out of order = 故障"},
{id:"d468",en:"We're having a small get-together on Saturday, you should come.",zh:"我們週六有個小聚會，你也來吧。",cat:"daily",sc:"鄰居社區",lv:2,note:"get-together = 聚會"},
{id:"d469",en:"Someone keeps parking in my spot.",zh:"一直有人停在我的車位。",cat:"daily",sc:"鄰居社區",lv:2},
{id:"d470",en:"It's nice to have neighbors who look out for each other.",zh:"有會互相照應的鄰居真好。",cat:"daily",sc:"鄰居社區",lv:3,note:"look out for = 照應、照顧"},

/* ============ 旅遊英文 · 火車地鐵 ============ */
{id:"t241",en:"Which line goes to the city center?",zh:"哪一條線會到市中心？",cat:"travel",sc:"火車地鐵",lv:1},
{id:"t242",en:"Do I need to change trains?",zh:"我需要轉車嗎？",cat:"travel",sc:"火車地鐵",lv:1},
{id:"t243",en:"Excuse me, I think you're in my seat.",zh:"不好意思，你好像坐到我的位子了。",cat:"travel",sc:"火車地鐵",lv:1},
{id:"t244",en:"How many stops is it from here?",zh:"從這裡要坐幾站？",cat:"travel",sc:"火車地鐵",lv:1},
{id:"t245",en:"I'd like a round-trip ticket to Oxford.",zh:"我要一張到牛津的來回票。",cat:"travel",sc:"火車地鐵",lv:2,note:"round-trip = 來回；one-way = 單程"},
{id:"t246",en:"Which platform does the train leave from?",zh:"火車從哪個月台出發？",cat:"travel",sc:"火車地鐵",lv:2},
{id:"t247",en:"I think I missed my stop.",zh:"我好像坐過站了。",cat:"travel",sc:"火車地鐵",lv:2},
{id:"t248",en:"Is there a day pass for unlimited rides?",zh:"有沒有可以無限搭乘的一日票？",cat:"travel",sc:"火車地鐵",lv:2},
{id:"t249",en:"The train is delayed by about fifteen minutes.",zh:"火車大約誤點十五分鐘。",cat:"travel",sc:"火車地鐵",lv:2},
{id:"t250",en:"Does this train stop at the airport?",zh:"這班車有停機場嗎？",cat:"travel",sc:"火車地鐵",lv:1},

/* ============ 旅遊英文 · 入境海關 ============ */
{id:"t251",en:"I'm here as a tourist, just for a week.",zh:"我是來觀光的，只待一個禮拜。",cat:"travel",sc:"入境海關",lv:1},
{id:"t252",en:"I'll be staying at a hotel downtown.",zh:"我會住在市區的一間飯店。",cat:"travel",sc:"入境海關",lv:1},
{id:"t253",en:"Here's my return ticket.",zh:"這是我的回程機票。",cat:"travel",sc:"入境海關",lv:1},
{id:"t254",en:"I have nothing to declare.",zh:"我沒有需要申報的東西。",cat:"travel",sc:"入境海關",lv:2,note:"declare = （海關）申報"},
{id:"t255",en:"These are gifts for my friends.",zh:"這些是要送朋友的禮物。",cat:"travel",sc:"入境海關",lv:1},
{id:"t256",en:"I'm visiting a friend who lives here.",zh:"我來拜訪住在這裡的朋友。",cat:"travel",sc:"入境海關",lv:1},
{id:"t257",en:"Do I need to fill out a customs form?",zh:"我需要填海關申報單嗎？",cat:"travel",sc:"入境海關",lv:2},
{id:"t258",en:"It's just some snacks and personal items.",zh:"只是一些零食和個人用品。",cat:"travel",sc:"入境海關",lv:2},
{id:"t259",en:"This is my first time visiting the country.",zh:"這是我第一次來這個國家。",cat:"travel",sc:"入境海關",lv:1},
{id:"t260",en:"I'm here for a business conference.",zh:"我來參加一場商務會議。",cat:"travel",sc:"入境海關",lv:2},

/* ============ 旅遊英文 · 博物館美術館 ============ */
{id:"t261",en:"What time does the museum close today?",zh:"博物館今天幾點關門？",cat:"travel",sc:"博物館美術館",lv:1},
{id:"t262",en:"Is admission free on certain days?",zh:"有哪幾天是免費入場的嗎？",cat:"travel",sc:"博物館美術館",lv:2,note:"admission = 入場（費）"},
{id:"t263",en:"Can I take photos in here?",zh:"這裡可以拍照嗎？",cat:"travel",sc:"博物館美術館",lv:1},
{id:"t264",en:"Do you have an audio guide in Chinese?",zh:"有中文的語音導覽嗎？",cat:"travel",sc:"博物館美術館",lv:2},
{id:"t265",en:"Where can I find the special exhibition?",zh:"特展在哪裡？",cat:"travel",sc:"博物館美術館",lv:2,note:"exhibition = 展覽"},
{id:"t266",en:"Is there a locker where I can leave my bag?",zh:"有沒有置物櫃可以放包包？",cat:"travel",sc:"博物館美術館",lv:2},
{id:"t267",en:"This painting is even more impressive in person.",zh:"這幅畫親眼看更震撼。",cat:"travel",sc:"博物館美術館",lv:2,note:"in person = 親自、親眼"},
{id:"t268",en:"Is there a guided tour in English?",zh:"有英文的導覽團嗎？",cat:"travel",sc:"博物館美術館",lv:1},
{id:"t269",en:"How long does it take to see the whole museum?",zh:"要逛完整間博物館大概要多久？",cat:"travel",sc:"博物館美術館",lv:2},
{id:"t270",en:"The gift shop is on the ground floor.",zh:"紀念品店在一樓。",cat:"travel",sc:"博物館美術館",lv:2,note:"英式 ground floor = 一樓"},

/* ============ 旅遊英文 · 主題樂園 ============ */
{id:"t271",en:"How long is the wait for this ride?",zh:"這個設施要排多久？",cat:"travel",sc:"主題樂園",lv:1},
{id:"t272",en:"Is there a height requirement?",zh:"有身高限制嗎？",cat:"travel",sc:"主題樂園",lv:2},
{id:"t273",en:"I'm too scared to go on the roller coaster.",zh:"我太怕了，不敢坐雲霄飛車。",cat:"travel",sc:"主題樂園",lv:1},
{id:"t274",en:"Should we get a fast pass to skip the lines?",zh:"我們要不要買快速通關不用排隊？",cat:"travel",sc:"主題樂園",lv:2},
{id:"t275",en:"What time does the parade start?",zh:"遊行幾點開始？",cat:"travel",sc:"主題樂園",lv:1},
{id:"t276",en:"Let's meet at the main entrance if we get separated.",zh:"如果走散了，就在大門口集合。",cat:"travel",sc:"主題樂園",lv:2},
{id:"t277",en:"That ride was absolutely terrifying!",zh:"那個設施真的超恐怖！",cat:"travel",sc:"主題樂園",lv:2},
{id:"t278",en:"Can I re-enter the park later today?",zh:"我今天晚點可以再入園嗎？",cat:"travel",sc:"主題樂園",lv:2},
{id:"t279",en:"The fireworks are the best part of the night.",zh:"煙火是晚上最精彩的部分。",cat:"travel",sc:"主題樂園",lv:1},
{id:"t280",en:"Where can I pick up the photo from the ride?",zh:"設施拍的照片要去哪裡領？",cat:"travel",sc:"主題樂園",lv:2},

/* ============ 旅遊英文 · 海灘水上活動 ============ */
{id:"t281",en:"Are there any jellyfish around here this time of year?",zh:"每年這個時候這附近有水母嗎？",cat:"travel",sc:"海灘水上活動",lv:2},
{id:"t282",en:"Can we rent a couple of beach chairs?",zh:"我們可以租兩張海灘椅嗎？",cat:"travel",sc:"海灘水上活動",lv:2},
{id:"t283",en:"Don't forget to put on sunscreen.",zh:"別忘了擦防曬。",cat:"travel",sc:"海灘水上活動",lv:1},
{id:"t284",en:"I've always wanted to try snorkeling.",zh:"我一直很想試試浮潛。",cat:"travel",sc:"海灘水上活動",lv:2,note:"snorkeling = 浮潛；diving = 潛水"},
{id:"t285",en:"The current is pretty strong today.",zh:"今天的海流蠻強的。",cat:"travel",sc:"海灘水上活動",lv:2,note:"current = 水流"},
{id:"t286",en:"Do I need any experience for the surfing lesson?",zh:"上衝浪課需要有經驗嗎？",cat:"travel",sc:"海灘水上活動",lv:2},
{id:"t287",en:"Is there a place to rinse off the sand?",zh:"有地方可以沖掉身上的沙嗎？",cat:"travel",sc:"海灘水上活動",lv:3,note:"rinse off = 沖洗掉"},
{id:"t288",en:"Let's watch the sunset from the pier.",zh:"我們去碼頭看夕陽吧。",cat:"travel",sc:"海灘水上活動",lv:2},
{id:"t289",en:"I got a little sunburned yesterday.",zh:"我昨天有點曬傷了。",cat:"travel",sc:"海灘水上活動",lv:2},
{id:"t290",en:"Are there lifeguards on duty?",zh:"有救生員在值班嗎？",cat:"travel",sc:"海灘水上活動",lv:2,note:"on duty = 值班中"},

/* ============ 旅遊英文 · 酒吧夜生活 ============ */
{id:"t291",en:"What do you have on tap?",zh:"你們有哪些生啤酒？",cat:"travel",sc:"酒吧夜生活",lv:2,note:"on tap = 桶裝現打的"},
{id:"t292",en:"Could I see the cocktail menu?",zh:"可以看一下調酒單嗎？",cat:"travel",sc:"酒吧夜生活",lv:1},
{id:"t293",en:"I'll have whatever you recommend.",zh:"你推薦什麼我就點什麼。",cat:"travel",sc:"酒吧夜生活",lv:2},
{id:"t294",en:"Something not too strong, please.",zh:"請給我不要太烈的。",cat:"travel",sc:"酒吧夜生活",lv:1},
{id:"t295",en:"This round is on me.",zh:"這一輪我請。",cat:"travel",sc:"酒吧夜生活",lv:2,note:"... is on me = 我請客"},
{id:"t296",en:"Can I start a tab?",zh:"可以先記帳，最後再一起結嗎？",cat:"travel",sc:"酒吧夜生活",lv:3,note:"start a tab = 開帳（最後一次結）"},
{id:"t297",en:"Is there live music tonight?",zh:"今晚有現場音樂嗎？",cat:"travel",sc:"酒吧夜生活",lv:1},
{id:"t298",en:"It's too loud in here, let's go somewhere quieter.",zh:"這裡太吵了，我們去安靜一點的地方吧。",cat:"travel",sc:"酒吧夜生活",lv:2},
{id:"t299",en:"I'm driving, so just a soda for me.",zh:"我要開車，給我汽水就好。",cat:"travel",sc:"酒吧夜生活",lv:2},
{id:"t300",en:"Is there a cover charge?",zh:"要收入場費嗎？",cat:"travel",sc:"酒吧夜生活",lv:3,note:"cover charge = 入場費、低消"},

/* ============ 旅遊英文 · 溫泉SPA ============ */
{id:"t301",en:"I'd like to book a sixty-minute massage.",zh:"我想預約六十分鐘的按摩。",cat:"travel",sc:"溫泉SPA",lv:2},
{id:"t302",en:"Could you go a little softer, please?",zh:"可以再輕一點嗎？",cat:"travel",sc:"溫泉SPA",lv:2},
{id:"t303",en:"A bit harder on my shoulders would be great.",zh:"肩膀的地方可以再大力一點。",cat:"travel",sc:"溫泉SPA",lv:2},
{id:"t304",en:"Are tattoos allowed in the hot spring?",zh:"有刺青可以泡溫泉嗎？",cat:"travel",sc:"溫泉SPA",lv:2},
{id:"t305",en:"Do I need to shower before getting in?",zh:"進去之前要先沖澡嗎？",cat:"travel",sc:"溫泉SPA",lv:1},
{id:"t306",en:"Are towels provided, or should I bring my own?",zh:"有提供毛巾嗎，還是我要自己帶？",cat:"travel",sc:"溫泉SPA",lv:2},
{id:"t307",en:"Is there a private bath we can reserve?",zh:"有可以預約的私人湯屋嗎？",cat:"travel",sc:"溫泉SPA",lv:2},
{id:"t308",en:"The water is a little too hot for me.",zh:"這水對我來說有點太燙。",cat:"travel",sc:"溫泉SPA",lv:1},
{id:"t309",en:"I feel so relaxed now.",zh:"我現在覺得好放鬆。",cat:"travel",sc:"溫泉SPA",lv:1},
{id:"t310",en:"Is the tip included in the price?",zh:"價格有含小費嗎？",cat:"travel",sc:"溫泉SPA",lv:2},

/* ============ 旅遊英文 · 航班延誤轉機 ============ */
{id:"t311",en:"My flight's been canceled, what are my options?",zh:"我的班機被取消了，我有哪些選擇？",cat:"travel",sc:"航班延誤轉機",lv:2},
{id:"t312",en:"I'm going to miss my connecting flight.",zh:"我會趕不上轉機的班機。",cat:"travel",sc:"航班延誤轉機",lv:2,note:"connecting flight = 轉機航班"},
{id:"t313",en:"Can you put me on the next available flight?",zh:"可以幫我排下一班有位子的班機嗎？",cat:"travel",sc:"航班延誤轉機",lv:2},
{id:"t314",en:"Will my luggage be transferred automatically?",zh:"我的行李會自動轉機嗎？",cat:"travel",sc:"航班延誤轉機",lv:2},
{id:"t315",en:"Where is the transfer desk?",zh:"轉機櫃檯在哪裡？",cat:"travel",sc:"航班延誤轉機",lv:1},
{id:"t316",en:"How long is the layover?",zh:"轉機要停留多久？",cat:"travel",sc:"航班延誤轉機",lv:2,note:"layover = 轉機停留"},
{id:"t317",en:"Will the airline cover the hotel tonight?",zh:"航空公司會負擔今晚的住宿嗎？",cat:"travel",sc:"航班延誤轉機",lv:3},
{id:"t318",en:"Can I get a meal voucher for the delay?",zh:"因為延誤，可以給我餐券嗎？",cat:"travel",sc:"航班延誤轉機",lv:3,note:"voucher = 兌換券"},
{id:"t319",en:"Do I need to go through security again?",zh:"我需要再過一次安檢嗎？",cat:"travel",sc:"航班延誤轉機",lv:2},
{id:"t320",en:"The departure gate has been changed to B12.",zh:"登機門改到 B12 了。",cat:"travel",sc:"航班延誤轉機",lv:2},

/* ============ 單字強化 · 新聞時事 ============ */
{id:"v151",en:"The government announced a new policy this morning.",zh:"政府今天早上宣布了一項新政策。",cat:"vocab",sc:"新聞時事",lv:2,note:"announce = 宣布；policy = 政策"},
{id:"v152",en:"Thousands of people gathered to protest the decision.",zh:"數千人聚集起來抗議這個決定。",cat:"vocab",sc:"新聞時事",lv:2,note:"protest = 抗議"},
{id:"v153",en:"The two countries finally reached an agreement.",zh:"兩國終於達成了協議。",cat:"vocab",sc:"新聞時事",lv:2,note:"reach an agreement = 達成協議"},
{id:"v154",en:"The company is facing growing criticism online.",zh:"那家公司在網路上面臨越來越多的批評。",cat:"vocab",sc:"新聞時事",lv:3,note:"criticism = 批評"},
{id:"v155",en:"Officials are investigating the cause of the fire.",zh:"官方正在調查起火原因。",cat:"vocab",sc:"新聞時事",lv:2,note:"investigate = 調查"},
{id:"v156",en:"The storm caused widespread power outages.",zh:"這場暴風雨造成大範圍停電。",cat:"vocab",sc:"新聞時事",lv:3,note:"widespread = 大範圍的；outage = 停電"},
{id:"v157",en:"Voter turnout was higher than expected.",zh:"投票率比預期的高。",cat:"vocab",sc:"新聞時事",lv:3,note:"turnout = 出席人數、投票率"},
{id:"v158",en:"The report has sparked a heated debate.",zh:"這份報告引發了激烈的辯論。",cat:"vocab",sc:"新聞時事",lv:3,note:"spark = 引發"},
{id:"v159",en:"According to a recent survey, most people prefer working from home.",zh:"根據最近的一項調查，大部分人比較喜歡在家工作。",cat:"vocab",sc:"新聞時事",lv:2,note:"survey = 調查"},
{id:"v160",en:"The city plans to expand its public transportation network.",zh:"市政府計畫擴大大眾運輸網路。",cat:"vocab",sc:"新聞時事",lv:2,note:"expand = 擴大"},

/* ============ 單字強化 · 科學自然 ============ */
{id:"v161",en:"Scientists have discovered a new species of frog.",zh:"科學家發現了一種新的青蛙物種。",cat:"vocab",sc:"科學自然",lv:2,note:"species = 物種（單複數同形）"},
{id:"v162",en:"Bees play a crucial role in pollinating crops.",zh:"蜜蜂在替農作物授粉上扮演關鍵角色。",cat:"vocab",sc:"科學自然",lv:3,note:"crucial = 關鍵的；pollinate = 授粉"},
{id:"v163",en:"The results of the experiment were surprising.",zh:"實驗結果令人意外。",cat:"vocab",sc:"科學自然",lv:2,note:"experiment = 實驗"},
{id:"v164",en:"Rising temperatures are melting the glaciers.",zh:"不斷上升的氣溫正在融化冰河。",cat:"vocab",sc:"科學自然",lv:3,note:"glacier = 冰河"},
{id:"v165",en:"The moon affects the ocean's tides.",zh:"月亮會影響海洋的潮汐。",cat:"vocab",sc:"科學自然",lv:2,note:"tide = 潮汐"},
{id:"v166",en:"This theory hasn't been proven yet.",zh:"這個理論還沒被證實。",cat:"vocab",sc:"科學自然",lv:2,note:"theory = 理論；prove = 證明"},
{id:"v167",en:"Some animals hibernate through the winter.",zh:"有些動物會冬眠度過冬天。",cat:"vocab",sc:"科學自然",lv:3,note:"hibernate = 冬眠"},
{id:"v168",en:"The volcano could erupt at any time.",zh:"這座火山隨時可能噴發。",cat:"vocab",sc:"科學自然",lv:2,note:"erupt = 噴發"},
{id:"v169",en:"Plants absorb carbon dioxide from the air.",zh:"植物會從空氣中吸收二氧化碳。",cat:"vocab",sc:"科學自然",lv:2,note:"absorb = 吸收"},
{id:"v170",en:"The data suggests a strong link between sleep and memory.",zh:"數據顯示睡眠和記憶有很強的關聯。",cat:"vocab",sc:"科學自然",lv:3,note:"suggest 在這裡是「顯示、暗示」"},

/* ============ 單字強化 · 商業職場 ============ */
{id:"v171",en:"We need to cut costs without lowering quality.",zh:"我們需要在不降低品質的情況下削減成本。",cat:"vocab",sc:"商業職場",lv:2,note:"cut costs = 削減成本"},
{id:"v172",en:"The deadline has been pushed back to Friday.",zh:"截止日延到星期五了。",cat:"vocab",sc:"商業職場",lv:2,note:"push back = 延後"},
{id:"v173",en:"Our main competitor just launched a similar product.",zh:"我們的主要競爭對手剛推出類似的產品。",cat:"vocab",sc:"商業職場",lv:2,note:"competitor = 競爭對手；launch = 推出"},
{id:"v174",en:"She was promoted to regional manager.",zh:"她被升為區域經理。",cat:"vocab",sc:"商業職場",lv:2,note:"promote = 升遷"},
{id:"v175",en:"The merger will be finalized next month.",zh:"這項合併案下個月會定案。",cat:"vocab",sc:"商業職場",lv:3,note:"merger = 合併；finalize = 敲定"},
{id:"v176",en:"We should negotiate a better contract.",zh:"我們應該談一份更好的合約。",cat:"vocab",sc:"商業職場",lv:2,note:"negotiate = 談判、協商"},
{id:"v177",en:"Customer feedback has been overwhelmingly positive.",zh:"客戶的回饋壓倒性地好。",cat:"vocab",sc:"商業職場",lv:3,note:"overwhelmingly = 壓倒性地"},
{id:"v178",en:"The startup is looking for new investors.",zh:"這間新創公司正在找新的投資人。",cat:"vocab",sc:"商業職場",lv:2,note:"startup = 新創公司"},
{id:"v179",en:"Let's prioritize the tasks that matter most.",zh:"我們先處理最重要的任務。",cat:"vocab",sc:"商業職場",lv:3,note:"prioritize = 排優先順序"},
{id:"v180",en:"He handed in his resignation yesterday.",zh:"他昨天遞了辭呈。",cat:"vocab",sc:"商業職場",lv:3,note:"resignation = 辭職、辭呈"},

/* ============ 單字強化 · 心理感受 ============ */
{id:"v181",en:"I've been feeling anxious about the future.",zh:"我最近對未來感到焦慮。",cat:"vocab",sc:"心理感受",lv:2,note:"anxious = 焦慮的"},
{id:"v182",en:"She's incredibly resilient after everything she's been through.",zh:"經歷了那麼多事，她的韌性真的很強。",cat:"vocab",sc:"心理感受",lv:3,note:"resilient = 有韌性的、能很快恢復的"},
{id:"v183",en:"I felt a sense of relief when it was over.",zh:"結束的時候我鬆了一口氣。",cat:"vocab",sc:"心理感受",lv:2,note:"relief = 如釋重負"},
{id:"v184",en:"He's reluctant to talk about his feelings.",zh:"他不太願意談自己的感受。",cat:"vocab",sc:"心理感受",lv:3,note:"reluctant = 不情願的"},
{id:"v185",en:"I'm grateful for all the support I've received.",zh:"我很感謝得到的所有支持。",cat:"vocab",sc:"心理感受",lv:2,note:"grateful = 感激的"},
{id:"v186",en:"The constant noise is really frustrating.",zh:"一直不停的噪音真的很讓人煩躁。",cat:"vocab",sc:"心理感受",lv:2,note:"frustrating = 令人沮喪、煩躁的"},
{id:"v187",en:"I'm starting to feel burned out at work.",zh:"我開始覺得工作讓我身心俱疲。",cat:"vocab",sc:"心理感受",lv:3,note:"burned out = 過勞、燃燒殆盡"},
{id:"v188",en:"It's normal to feel overwhelmed sometimes.",zh:"偶爾覺得招架不住是很正常的。",cat:"vocab",sc:"心理感受",lv:3,note:"overwhelmed = 不知所措、被壓垮的"},
{id:"v189",en:"He seemed indifferent to the news.",zh:"他對這個消息似乎無動於衷。",cat:"vocab",sc:"心理感受",lv:3,note:"indifferent = 漠不關心的"},
{id:"v190",en:"I felt nostalgic looking at our old photos.",zh:"看著我們的舊照片，我覺得好懷念。",cat:"vocab",sc:"心理感受",lv:3,note:"nostalgic = 懷舊的"},

/* ============ 單字強化 · 法律社會 ============ */
{id:"v191",en:"Everyone has the right to a fair trial.",zh:"每個人都有接受公平審判的權利。",cat:"vocab",sc:"法律社會",lv:3,note:"trial = 審判"},
{id:"v192",en:"The new law will take effect next year.",zh:"新法會在明年生效。",cat:"vocab",sc:"法律社會",lv:2,note:"take effect = 生效"},
{id:"v193",en:"Smoking is prohibited in all public buildings.",zh:"所有公共建築都禁止吸菸。",cat:"vocab",sc:"法律社會",lv:3,note:"prohibit = 禁止"},
{id:"v194",en:"He was fined for parking illegally.",zh:"他因為違規停車被罰款。",cat:"vocab",sc:"法律社會",lv:2,note:"fine 當動詞 = 罰款"},
{id:"v195",en:"The suspect denied all the charges.",zh:"嫌犯否認所有的指控。",cat:"vocab",sc:"法律社會",lv:3,note:"suspect = 嫌犯；charge = 指控"},
{id:"v196",en:"Access to education should be equal for everyone.",zh:"受教育的機會應該人人平等。",cat:"vocab",sc:"法律社會",lv:2,note:"access = 取得的機會"},
{id:"v197",en:"The population is aging rapidly.",zh:"人口正在快速老化。",cat:"vocab",sc:"法律社會",lv:2,note:"aging = 老化"},
{id:"v198",en:"Many volunteers donated their time to help.",zh:"很多志工貢獻時間來幫忙。",cat:"vocab",sc:"法律社會",lv:2,note:"volunteer = 志工；donate = 捐贈"},
{id:"v199",en:"Housing prices have become unaffordable for young people.",zh:"房價已經高到年輕人負擔不起。",cat:"vocab",sc:"法律社會",lv:3,note:"unaffordable = 負擔不起的"},
{id:"v200",en:"You should read the terms before you sign.",zh:"簽名之前你應該先看過條款。",cat:"vocab",sc:"法律社會",lv:2,note:"terms = 條款"},

/* ============ 單字強化 · 文化藝術 ============ */
{id:"v201",en:"The festival celebrates the region's rich heritage.",zh:"這個節慶是為了慶祝當地豐富的文化傳統。",cat:"vocab",sc:"文化藝術",lv:3,note:"heritage = 文化遺產、傳統"},
{id:"v202",en:"Her latest novel became an instant bestseller.",zh:"她的最新小說一出版就成了暢銷書。",cat:"vocab",sc:"文化藝術",lv:2,note:"novel = 長篇小說"},
{id:"v203",en:"The architecture here is absolutely stunning.",zh:"這裡的建築真的美得驚人。",cat:"vocab",sc:"文化藝術",lv:2,note:"architecture = 建築；stunning = 驚艷的"},
{id:"v204",en:"The film was inspired by a true story.",zh:"這部電影的靈感來自真實故事。",cat:"vocab",sc:"文化藝術",lv:2,note:"be inspired by = 受……啟發"},
{id:"v205",en:"This tradition has been passed down for generations.",zh:"這個傳統已經傳承好幾代了。",cat:"vocab",sc:"文化藝術",lv:3,note:"pass down = 傳承下去"},
{id:"v206",en:"The orchestra gave a remarkable performance.",zh:"管弦樂團的演出非常精彩。",cat:"vocab",sc:"文化藝術",lv:3,note:"remarkable = 出色的；performance = 表演"},
{id:"v207",en:"The exhibit features works by local artists.",zh:"這次展覽以在地藝術家的作品為主。",cat:"vocab",sc:"文化藝術",lv:3,note:"feature 當動詞 = 以……為特色"},
{id:"v208",en:"I find modern art hard to interpret.",zh:"我覺得現代藝術很難理解。",cat:"vocab",sc:"文化藝術",lv:3,note:"interpret = 詮釋、理解"},
{id:"v209",en:"The play received mixed reviews from critics.",zh:"這齣戲在評論家之間褒貶不一。",cat:"vocab",sc:"文化藝術",lv:3,note:"mixed reviews = 褒貶不一；critic = 評論家"},
{id:"v210",en:"Street food is a big part of the local culture.",zh:"路邊小吃是當地文化很重要的一部分。",cat:"vocab",sc:"文化藝術",lv:1}

]);
