/* Echo 英語 — 擴充句庫 3（繼續往 1000 句邁進）
   欄位說明同 bank.js／bank2.js
*/
window.BANK = (window.BANK||[]).concat([

/* ============ 日常會話 · 道別 ============ */
{id:"d251",en:"I should get going, it's getting late.",zh:"我該走了，有點晚了。",cat:"daily",sc:"道別",lv:1},
{id:"d252",en:"Take care, and let's catch up again soon.",zh:"保重，我們改天再聚。",cat:"daily",sc:"道別",lv:2,note:"catch up = 聚聚聊近況"},
{id:"d253",en:"It was great seeing you again.",zh:"很高興再見到你。",cat:"daily",sc:"道別",lv:1},
{id:"d254",en:"Drive safe on your way home.",zh:"回家路上開車小心。",cat:"daily",sc:"道別",lv:1},
{id:"d255",en:"Let's not leave it so long next time.",zh:"下次別隔這麼久才見面。",cat:"daily",sc:"道別",lv:2},
{id:"d256",en:"I've got an early start tomorrow, so I'll head out now.",zh:"我明天要早起，所以我先走了。",cat:"daily",sc:"道別",lv:2},
{id:"d257",en:"Say goodbye to everyone for me.",zh:"幫我跟大家說再見。",cat:"daily",sc:"道別",lv:1},
{id:"d258",en:"I'll walk you to the door.",zh:"我送你到門口。",cat:"daily",sc:"道別",lv:1},
{id:"d259",en:"Let's grab dinner again sometime.",zh:"找時間再一起吃頓飯吧。",cat:"daily",sc:"道別",lv:1},
{id:"d260",en:"Safe travels, text me when you land.",zh:"一路平安，到了傳個訊息給我。",cat:"daily",sc:"道別",lv:2},

/* ============ 日常會話 · 求助幫忙 ============ */
{id:"d261",en:"Could you give me a hand with this?",zh:"可以幫我一下這個嗎？",cat:"daily",sc:"求助幫忙",lv:1},
{id:"d262",en:"I'm a bit stuck, could you take a look?",zh:"我有點卡住了，你能看一下嗎？",cat:"daily",sc:"求助幫忙",lv:2},
{id:"d263",en:"Would you mind helping me carry this upstairs?",zh:"你介意幫我把這個搬上樓嗎？",cat:"daily",sc:"求助幫忙",lv:2},
{id:"d264",en:"I could really use some advice right now.",zh:"我現在真的需要一些建議。",cat:"daily",sc:"求助幫忙",lv:2},
{id:"d265",en:"Is there someone who can walk me through this?",zh:"有沒有人可以帶我了解一下這個？",cat:"daily",sc:"求助幫忙",lv:2},
{id:"d266",en:"I don't know who else to ask.",zh:"我不知道還能問誰。",cat:"daily",sc:"求助幫忙",lv:1},
{id:"d267",en:"Could you cover for me for a few minutes?",zh:"可以幫我代班幾分鐘嗎？",cat:"daily",sc:"求助幫忙",lv:2,note:"cover for = 代替、幫忙代班"},
{id:"d268",en:"I hate to ask, but could you help me out?",zh:"我實在不好意思開口，但可以幫幫我嗎？",cat:"daily",sc:"求助幫忙",lv:2},
{id:"d269",en:"Let me know if you ever need a hand too.",zh:"如果你也需要幫忙就跟我說。",cat:"daily",sc:"求助幫忙",lv:1},
{id:"d270",en:"Thanks for bailing me out back there.",zh:"謝謝你剛剛幫我解圍。",cat:"daily",sc:"求助幫忙",lv:3,note:"bail someone out = 幫人擺脫困境"},

/* ============ 日常會話 · 環保永續 ============ */
{id:"d271",en:"I'm trying to cut down on plastic.",zh:"我在盡量減少使用塑膠製品。",cat:"daily",sc:"環保永續",lv:2},
{id:"d272",en:"Do you recycle at home?",zh:"你在家會做資源回收嗎？",cat:"daily",sc:"環保永續",lv:1},
{id:"d273",en:"I bring my own bag whenever I go shopping.",zh:"我每次去購物都會自己帶購物袋。",cat:"daily",sc:"環保永續",lv:1},
{id:"d274",en:"It's better for the environment to take public transit.",zh:"搭大眾運輸對環境比較好。",cat:"daily",sc:"環保永續",lv:2},
{id:"d275",en:"We should waste less food.",zh:"我們應該少浪費食物。",cat:"daily",sc:"環保永續",lv:1},
{id:"d276",en:"I switched to a reusable water bottle.",zh:"我改用可重複使用的水瓶了。",cat:"daily",sc:"環保永續",lv:2},
{id:"d277",en:"Composting is easier than I thought.",zh:"做堆肥比我想的還簡單。",cat:"daily",sc:"環保永續",lv:3,note:"composting = 堆肥"},
{id:"d278",en:"Fast fashion isn't great for the planet.",zh:"快時尚對地球其實不太好。",cat:"daily",sc:"環保永續",lv:3},
{id:"d279",en:"Let's carpool to save on gas.",zh:"我們共乘一台車省點油錢吧。",cat:"daily",sc:"環保永續",lv:2,note:"carpool = 共乘"},
{id:"d280",en:"Small habits can make a big difference.",zh:"小小的習慣也能帶來很大的改變。",cat:"daily",sc:"環保永續",lv:2},

/* ============ 日常會話 · 育兒 ============ */
{id:"d281",en:"My daughter just started kindergarten.",zh:"我女兒剛開始上幼稚園。",cat:"daily",sc:"育兒",lv:1},
{id:"d282",en:"He's going through the terrible twos.",zh:"他正在經歷所謂的兩歲叛逆期。",cat:"daily",sc:"育兒",lv:3,note:"terrible twos = 兩歲小孩的叛逆期"},
{id:"d283",en:"I need to pick up my kid from school.",zh:"我需要去學校接小孩。",cat:"daily",sc:"育兒",lv:1},
{id:"d284",en:"She's a very picky eater.",zh:"她吃東西很挑食。",cat:"daily",sc:"育兒",lv:1},
{id:"d285",en:"Bedtime is always a struggle.",zh:"哄睡總是很掙扎。",cat:"daily",sc:"育兒",lv:2},
{id:"d286",en:"He's obsessed with dinosaurs right now.",zh:"他現在超級迷恐龍。",cat:"daily",sc:"育兒",lv:2},
{id:"d287",en:"We're trying to limit his screen time.",zh:"我們在盡量限制他看螢幕的時間。",cat:"daily",sc:"育兒",lv:2},
{id:"d288",en:"Parenting is way harder than I expected.",zh:"當父母比我想的難多了。",cat:"daily",sc:"育兒",lv:2},
{id:"d289",en:"She just took her first steps.",zh:"她剛學會走第一步。",cat:"daily",sc:"育兒",lv:1},
{id:"d290",en:"I need to sign him up for summer camp.",zh:"我得幫他報名夏令營。",cat:"daily",sc:"育兒",lv:2},

/* ============ 日常會話 · 寵物 ============ */
{id:"d291",en:"My dog won't stop barking at the door.",zh:"我的狗一直對著門叫個不停。",cat:"daily",sc:"寵物",lv:1},
{id:"d292",en:"I need to take my cat to the vet.",zh:"我要帶我的貓去看獸醫。",cat:"daily",sc:"寵物",lv:1},
{id:"d293",en:"He's such a picky eater for a dog.",zh:"牠當一隻狗來說吃得很挑。",cat:"daily",sc:"寵物",lv:2},
{id:"d294",en:"My cat knocked everything off the table again.",zh:"我的貓又把桌上的東西全弄掉了。",cat:"daily",sc:"寵物",lv:1},
{id:"d295",en:"We just adopted a puppy last week.",zh:"我們上週剛領養了一隻小狗。",cat:"daily",sc:"寵物",lv:1},
{id:"d296",en:"She sheds so much fur everywhere.",zh:"牠掉毛掉得到處都是。",cat:"daily",sc:"寵物",lv:2,note:"shed = （動物）掉毛"},
{id:"d297",en:"I have to walk the dog before work.",zh:"我上班前得先遛狗。",cat:"daily",sc:"寵物",lv:1},
{id:"d298",en:"He's finally house-trained.",zh:"牠終於學會在家裡定點上廁所了。",cat:"daily",sc:"寵物",lv:3,note:"house-trained = （寵物）受過如廁訓練"},
{id:"d299",en:"My cat's been acting kind of off lately.",zh:"我的貓最近怪怪的。",cat:"daily",sc:"寵物",lv:2},
{id:"d300",en:"Could you feed my fish while I'm away?",zh:"我不在的時候可以幫我餵魚嗎？",cat:"daily",sc:"寵物",lv:1},

/* ============ 日常會話 · 理財投資 ============ */
{id:"d301",en:"I've started putting money into index funds.",zh:"我開始把錢投入指數型基金。",cat:"daily",sc:"理財投資",lv:3},
{id:"d302",en:"I'm trying to build up an emergency fund.",zh:"我在努力存一筆緊急預備金。",cat:"daily",sc:"理財投資",lv:2},
{id:"d303",en:"The market's been pretty volatile lately.",zh:"最近市場波動蠻大的。",cat:"daily",sc:"理財投資",lv:3,note:"volatile = 波動劇烈的"},
{id:"d304",en:"I should really start budgeting better.",zh:"我真的該好好做預算規劃了。",cat:"daily",sc:"理財投資",lv:2},
{id:"d305",en:"He lost a lot of money on that investment.",zh:"他在那筆投資上虧了不少錢。",cat:"daily",sc:"理財投資",lv:1},
{id:"d306",en:"I set aside a bit of my paycheck every month.",zh:"我每個月都會從薪水裡撥一點出來存。",cat:"daily",sc:"理財投資",lv:2},
{id:"d307",en:"It's important to diversify your investments.",zh:"分散投資很重要。",cat:"daily",sc:"理財投資",lv:3,note:"diversify = 使多樣化、分散"},
{id:"d308",en:"I'm still paying off my student loans.",zh:"我還在還學貸。",cat:"daily",sc:"理財投資",lv:2},
{id:"d309",en:"We're saving up for a down payment on a house.",zh:"我們在存買房的頭期款。",cat:"daily",sc:"理財投資",lv:2},
{id:"d310",en:"I'd rather save than splurge on stuff I don't need.",zh:"我寧願存錢也不要亂花在不需要的東西上。",cat:"daily",sc:"理財投資",lv:3,note:"splurge = 揮霍、大肆花錢"},

/* ============ 日常會話 · 職涯發展 ============ */
{id:"d311",en:"I'm thinking about switching careers.",zh:"我在考慮轉換跑道。",cat:"daily",sc:"職涯發展",lv:2},
{id:"d312",en:"I got offered a promotion last week.",zh:"我上週被提出升遷。",cat:"daily",sc:"職涯發展",lv:1},
{id:"d313",en:"I feel like I've hit a ceiling at this job.",zh:"我覺得在這份工作上已經到瓶頸了。",cat:"daily",sc:"職涯發展",lv:3,note:"hit a ceiling = 遇到發展上限"},
{id:"d314",en:"I'm updating my resume this weekend.",zh:"我這週末要更新我的履歷。",cat:"daily",sc:"職涯發展",lv:1},
{id:"d315",en:"Networking really does make a difference.",zh:"拓展人脈真的有差。",cat:"daily",sc:"職涯發展",lv:2,note:"networking = 建立人脈"},
{id:"d316",en:"I have an interview lined up for next week.",zh:"我下週已經安排了一場面試。",cat:"daily",sc:"職涯發展",lv:2},
{id:"d317",en:"I want to find something more fulfilling.",zh:"我想找一份更有成就感的工作。",cat:"daily",sc:"職涯發展",lv:3,note:"fulfilling = 有成就感的"},
{id:"d318",en:"She got headhunted by another company.",zh:"她被另一間公司挖角了。",cat:"daily",sc:"職涯發展",lv:3,note:"headhunted = 被獵才、被挖角"},
{id:"d319",en:"I'm not sure this job is the right fit for me.",zh:"我不確定這份工作適不適合我。",cat:"daily",sc:"職涯發展",lv:2},
{id:"d320",en:"I finally negotiated a higher salary.",zh:"我終於談成了更高的薪水。",cat:"daily",sc:"職涯發展",lv:2},

/* ============ 日常會話 · 安慰打氣 ============ */
{id:"d321",en:"It's going to be okay, take your time.",zh:"會沒事的，你慢慢來。",cat:"daily",sc:"安慰打氣",lv:1},
{id:"d322",en:"I'm really sorry you're going through this.",zh:"很遺憾你正經歷這些。",cat:"daily",sc:"安慰打氣",lv:2},
{id:"d323",en:"You're not alone in this.",zh:"這件事你不是一個人在面對。",cat:"daily",sc:"安慰打氣",lv:2},
{id:"d324",en:"It's okay to not be okay sometimes.",zh:"有時候不開心也沒關係。",cat:"daily",sc:"安慰打氣",lv:2},
{id:"d325",en:"Let me know if you need someone to talk to.",zh:"如果你需要人聊聊，隨時找我。",cat:"daily",sc:"安慰打氣",lv:1},
{id:"d326",en:"That sounds really tough, I'm sorry.",zh:"聽起來真的很不容易，我很遺憾。",cat:"daily",sc:"安慰打氣",lv:2},
{id:"d327",en:"Things will get better with time.",zh:"事情會隨著時間慢慢變好的。",cat:"daily",sc:"安慰打氣",lv:1},
{id:"d328",en:"I'm here for you, whatever you need.",zh:"不管你需要什麼，我都在。",cat:"daily",sc:"安慰打氣",lv:1},
{id:"d329",en:"Don't be too hard on yourself over this.",zh:"別因為這件事太苛責自己。",cat:"daily",sc:"安慰打氣",lv:2},
{id:"d330",en:"You've handled worse than this before.",zh:"你以前也撐過比這更難的事。",cat:"daily",sc:"安慰打氣",lv:2},

/* ============ 日常會話 · 意見衝突 ============ */
{id:"d331",en:"I see it a bit differently.",zh:"我看法有點不太一樣。",cat:"daily",sc:"意見衝突",lv:1},
{id:"d332",en:"I understand your point, but I disagree.",zh:"我懂你的意思，但我不同意。",cat:"daily",sc:"意見衝突",lv:2},
{id:"d333",en:"Let's agree to disagree on this one.",zh:"這件事我們就各持己見吧。",cat:"daily",sc:"意見衝突",lv:3,note:"agree to disagree = 同意各自保留意見"},
{id:"d334",en:"That's a fair point, but consider this.",zh:"你說得有道理，但想想這個。",cat:"daily",sc:"意見衝突",lv:2},
{id:"d335",en:"I don't think that's entirely accurate.",zh:"我不覺得那完全正確。",cat:"daily",sc:"意見衝突",lv:2},
{id:"d336",en:"We just have different priorities, I guess.",zh:"我想我們只是重視的東西不一樣。",cat:"daily",sc:"意見衝突",lv:2},
{id:"d337",en:"Can we table this discussion for later?",zh:"我們可以晚點再討論這個嗎？",cat:"daily",sc:"意見衝突",lv:3,note:"table a discussion = 暫緩討論"},
{id:"d338",en:"I'm not fully convinced by that argument.",zh:"那個論點我沒有完全被說服。",cat:"daily",sc:"意見衝突",lv:3},
{id:"d339",en:"Let's just agree on a middle ground.",zh:"我們就找個折衷方案吧。",cat:"daily",sc:"意見衝突",lv:2,note:"middle ground = 折衷方案"},
{id:"d340",en:"I hear what you're saying, but I still feel differently.",zh:"我懂你的意思，但我還是有不同的感受。",cat:"daily",sc:"意見衝突",lv:2},

/* ============ 日常會話 · 時間管理 ============ */
{id:"d341",en:"I'm terrible at managing my time.",zh:"我很不擅長管理時間。",cat:"daily",sc:"時間管理",lv:1},
{id:"d342",en:"I keep putting this task off.",zh:"我一直把這個任務往後拖延。",cat:"daily",sc:"時間管理",lv:2},
{id:"d343",en:"I need to prioritize what's actually urgent.",zh:"我需要優先處理真正緊急的事。",cat:"daily",sc:"時間管理",lv:2},
{id:"d344",en:"I always underestimate how long things take.",zh:"我總是低估事情要花多久時間。",cat:"daily",sc:"時間管理",lv:2},
{id:"d345",en:"Let's block out some time for this tomorrow.",zh:"我們明天先排一段時間來處理這個。",cat:"daily",sc:"時間管理",lv:2,note:"block out time = 預留時間"},
{id:"d346",en:"I'm trying to cut down on distractions.",zh:"我在努力減少讓自己分心的事物。",cat:"daily",sc:"時間管理",lv:2},
{id:"d347",en:"I work better under a bit of pressure.",zh:"我在一點壓力下反而工作效率更好。",cat:"daily",sc:"時間管理",lv:1},
{id:"d348",en:"I should really stop multitasking so much.",zh:"我真的該少一心多用。",cat:"daily",sc:"時間管理",lv:2},
{id:"d349",en:"I lost track of time completely.",zh:"我完全忘了時間過了多久。",cat:"daily",sc:"時間管理",lv:1},
{id:"d350",en:"Let's set a deadline so we actually finish this.",zh:"我們訂個期限，這樣才會真的完成。",cat:"daily",sc:"時間管理",lv:1},

/* ============ 日常會話 · 網路購物退換貨 ============ */
{id:"d351",en:"This isn't what I ordered.",zh:"這不是我訂的東西。",cat:"daily",sc:"網路購物退換貨",lv:1},
{id:"d352",en:"How do I request a refund?",zh:"我要怎麼申請退款？",cat:"daily",sc:"網路購物退換貨",lv:1},
{id:"d353",en:"The item arrived damaged.",zh:"商品送到時是壞的。",cat:"daily",sc:"網路購物退換貨",lv:1},
{id:"d354",en:"Do I need to pay for return shipping?",zh:"退貨運費需要我自己出嗎？",cat:"daily",sc:"網路購物退換貨",lv:2},
{id:"d355",en:"My package still hasn't arrived yet.",zh:"我的包裹到現在都還沒送到。",cat:"daily",sc:"網路購物退換貨",lv:1},
{id:"d356",en:"Can I exchange this for a different size?",zh:"我可以換成不同的尺寸嗎？",cat:"daily",sc:"網路購物退換貨",lv:1},
{id:"d357",en:"The tracking number shows it as delivered, but I never got it.",zh:"追蹤顯示已送達，但我根本沒收到。",cat:"daily",sc:"網路購物退換貨",lv:3},
{id:"d358",en:"I'd like to cancel this order before it ships.",zh:"我想在出貨前取消這筆訂單。",cat:"daily",sc:"網路購物退換貨",lv:2},
{id:"d359",en:"It doesn't look anything like the photos.",zh:"它跟照片完全不一樣。",cat:"daily",sc:"網路購物退換貨",lv:1},
{id:"d360",en:"How long does the refund usually take?",zh:"退款通常要多久時間？",cat:"daily",sc:"網路購物退換貨",lv:1},

/* ============ 旅遊英文 · 搭船渡輪 ============ */
{id:"t171",en:"What time does the next ferry leave?",zh:"下一班渡輪幾點出發？",cat:"travel",sc:"搭船渡輪",lv:1},
{id:"t172",en:"Is there an indoor seating area on the boat?",zh:"船上有室內座位區嗎？",cat:"travel",sc:"搭船渡輪",lv:1},
{id:"t173",en:"I get seasick pretty easily.",zh:"我很容易暈船。",cat:"travel",sc:"搭船渡輪",lv:2},
{id:"t174",en:"How long is the crossing?",zh:"航程要多久？",cat:"travel",sc:"搭船渡輪",lv:1,note:"crossing = 渡海航程"},
{id:"t175",en:"Do we need to book tickets in advance?",zh:"我們需要事先訂票嗎？",cat:"travel",sc:"搭船渡輪",lv:1},
{id:"t176",en:"Is it okay to bring luggage on board?",zh:"可以帶行李上船嗎？",cat:"travel",sc:"搭船渡輪",lv:1},
{id:"t177",en:"The sea's pretty rough today.",zh:"今天海象不太好。",cat:"travel",sc:"搭船渡輪",lv:2,note:"rough sea = 海象不佳、風浪大"},
{id:"t178",en:"Where do we board the ferry?",zh:"我們要去哪裡登船？",cat:"travel",sc:"搭船渡輪",lv:1},
{id:"t179",en:"Is there a car deck on this ferry?",zh:"這艘渡輪有車輛甲板嗎？",cat:"travel",sc:"搭船渡輪",lv:2},
{id:"t180",en:"We just missed the last ferry back.",zh:"我們剛好錯過最後一班回程的渡輪。",cat:"travel",sc:"搭船渡輪",lv:2},

/* ============ 旅遊英文 · 露營野餐 ============ */
{id:"t181",en:"Is this a good spot to set up camp?",zh:"這裡適合紮營嗎？",cat:"travel",sc:"露營野餐",lv:1},
{id:"t182",en:"Do we need a permit to camp here?",zh:"在這裡露營需要許可證嗎？",cat:"travel",sc:"露營野餐",lv:2},
{id:"t183",en:"Let's lay out the picnic blanket over there.",zh:"我們把野餐墊鋪在那邊吧。",cat:"travel",sc:"露營野餐",lv:1},
{id:"t184",en:"Did you bring bug spray?",zh:"你有帶防蚊液嗎？",cat:"travel",sc:"露營野餐",lv:1},
{id:"t185",en:"We should gather firewood before it gets dark.",zh:"我們該在天黑前撿些柴火。",cat:"travel",sc:"露營野餐",lv:2},
{id:"t186",en:"Is there a water source nearby?",zh:"附近有水源嗎？",cat:"travel",sc:"露營野餐",lv:1},
{id:"t187",en:"Make sure the campfire's completely out before we leave.",zh:"離開前要確定營火完全熄滅。",cat:"travel",sc:"露營野餐",lv:2},
{id:"t188",en:"The tent's a bit tricky to set up.",zh:"這帳篷有點難搭。",cat:"travel",sc:"露營野餐",lv:1},
{id:"t189",en:"Let's pack some snacks for the hike.",zh:"我們準備一些點心帶去健行。",cat:"travel",sc:"露營野餐",lv:1},
{id:"t190",en:"The view from the campsite is incredible.",zh:"營地看出去的景色美得不得了。",cat:"travel",sc:"露營野餐",lv:1},

/* ============ 旅遊英文 · 市集殺價 ============ */
{id:"t191",en:"Can you go any lower on the price?",zh:"價錢可以再低一點嗎？",cat:"travel",sc:"市集殺價",lv:1},
{id:"t192",en:"Is that your best price?",zh:"這是你能給的最低價嗎？",cat:"travel",sc:"市集殺價",lv:2},
{id:"t193",en:"I'll take two if you give me a discount.",zh:"如果有折扣我就買兩個。",cat:"travel",sc:"市集殺價",lv:2},
{id:"t194",en:"That's a bit too expensive for me.",zh:"這對我來說有點太貴了。",cat:"travel",sc:"市集殺價",lv:1},
{id:"t195",en:"Do you take cash instead?",zh:"你們收現金嗎？",cat:"travel",sc:"市集殺價",lv:1},
{id:"t196",en:"I saw the same thing cheaper down the street.",zh:"我在前面那條街看到一樣的東西比較便宜。",cat:"travel",sc:"市集殺價",lv:2},
{id:"t197",en:"Could you throw in something extra?",zh:"可以多送我一點什麼嗎？",cat:"travel",sc:"市集殺價",lv:3,note:"throw in = 額外附贈"},
{id:"t198",en:"Let's just settle on this price.",zh:"我們就用這個價錢成交吧。",cat:"travel",sc:"市集殺價",lv:2},
{id:"t199",en:"I'm just browsing for now, thanks.",zh:"我先看看，謝謝。",cat:"travel",sc:"市集殺價",lv:1},
{id:"t200",en:"Is the price negotiable?",zh:"這個價錢可以談嗎？",cat:"travel",sc:"市集殺價",lv:2,note:"negotiable = 可協商的"},

/* ============ 旅遊英文 · 天氣災害應變 ============ */
{id:"t201",en:"Our flight got delayed because of the storm.",zh:"我們的班機因為暴風雨延誤了。",cat:"travel",sc:"天氣災害應變",lv:2},
{id:"t202",en:"Is it safe to go out in this weather?",zh:"這種天氣出門安全嗎？",cat:"travel",sc:"天氣災害應變",lv:1},
{id:"t203",en:"The road ahead is flooded.",zh:"前面的路淹水了。",cat:"travel",sc:"天氣災害應變",lv:2},
{id:"t204",en:"We should probably wait out the storm here.",zh:"我們可能該在這裡等暴風雨過去。",cat:"travel",sc:"天氣災害應變",lv:2,note:"wait out = 等（壞天氣）過去"},
{id:"t205",en:"Do you know if the ferry's still running?",zh:"你知道渡輪還有沒有在開嗎？",cat:"travel",sc:"天氣災害應變",lv:1},
{id:"t206",en:"It's too windy to go up the mountain today.",zh:"今天風太大了不適合上山。",cat:"travel",sc:"天氣災害應變",lv:1},
{id:"t207",en:"We had to change our plans because of the typhoon.",zh:"我們因為颱風不得不改變計畫。",cat:"travel",sc:"天氣災害應變",lv:2},
{id:"t208",en:"Is there an indoor alternative for today?",zh:"今天有沒有室內的替代行程？",cat:"travel",sc:"天氣災害應變",lv:2},
{id:"t209",en:"The visibility is really poor right now.",zh:"現在能見度很差。",cat:"travel",sc:"天氣災害應變",lv:3,note:"visibility = 能見度"},
{id:"t210",en:"Let's check the forecast before we head out.",zh:"我們出發前先看一下天氣預報吧。",cat:"travel",sc:"天氣災害應變",lv:1},

/* ============ 旅遊英文 · 異地用餐 ============ */
{id:"t211",en:"Does this dish contain any nuts?",zh:"這道菜有含堅果嗎？",cat:"travel",sc:"異地用餐",lv:1},
{id:"t212",en:"I'm allergic to shellfish.",zh:"我對甲殼類海鮮過敏。",cat:"travel",sc:"異地用餐",lv:2,note:"shellfish = 甲殼類海鮮"},
{id:"t213",en:"Could you make this without dairy?",zh:"這道菜可以不加乳製品嗎？",cat:"travel",sc:"異地用餐",lv:2},
{id:"t214",en:"Do you have any vegetarian options?",zh:"你們有素食選項嗎？",cat:"travel",sc:"異地用餐",lv:1},
{id:"t215",en:"Is this spicy? I can't handle spicy food.",zh:"這個辣嗎？我不太能吃辣。",cat:"travel",sc:"異地用餐",lv:1},
{id:"t216",en:"Could I get this to go instead?",zh:"這個可以改成外帶嗎？",cat:"travel",sc:"異地用餐",lv:1},
{id:"t217",en:"What do you recommend for someone who's never had this before?",zh:"第一次吃這個的話你推薦什麼？",cat:"travel",sc:"異地用餐",lv:2},
{id:"t218",en:"Is tap water safe to drink here?",zh:"這裡的自來水可以喝嗎？",cat:"travel",sc:"異地用餐",lv:1},
{id:"t219",en:"Could we get separate checks, please?",zh:"可以幫我們分開結帳嗎？",cat:"travel",sc:"異地用餐",lv:2},
{id:"t220",en:"That was honestly one of the best meals I've had.",zh:"老實說這是我吃過最好吃的一餐之一。",cat:"travel",sc:"異地用餐",lv:2},

/* ============ 旅遊英文 · 背包客棧交流 ============ */
{id:"t221",en:"Which bunk is mine?",zh:"我睡哪個床位？",cat:"travel",sc:"背包客棧交流",lv:1,note:"bunk = 上下鋪床位"},
{id:"t222",en:"Is there a common kitchen we can use?",zh:"有共用廚房可以用嗎？",cat:"travel",sc:"背包客棧交流",lv:1},
{id:"t223",en:"Do you know any other travelers doing the same route?",zh:"你認識其他走同樣路線的旅人嗎？",cat:"travel",sc:"背包客棧交流",lv:2},
{id:"t224",en:"What time do they lock the doors at night?",zh:"晚上幾點會鎖門？",cat:"travel",sc:"背包客棧交流",lv:1},
{id:"t225",en:"Is there a curfew here?",zh:"這裡有門禁時間嗎？",cat:"travel",sc:"背包客棧交流",lv:2,note:"curfew = 門禁、宵禁"},
{id:"t226",en:"Do you have lockers for our valuables?",zh:"有可以放貴重物品的置物櫃嗎？",cat:"travel",sc:"背包客棧交流",lv:2},
{id:"t227",en:"Want to grab dinner with the rest of us tonight?",zh:"今晚要不要跟我們一起去吃晚餐？",cat:"travel",sc:"背包客棧交流",lv:1},
{id:"t228",en:"How long have you been traveling for?",zh:"你旅行多久了？",cat:"travel",sc:"背包客棧交流",lv:1},
{id:"t229",en:"This place has such a nice, laid-back vibe.",zh:"這個地方氣氛很輕鬆自在。",cat:"travel",sc:"背包客棧交流",lv:2,note:"laid-back = 輕鬆自在的"},
{id:"t230",en:"Any tips for where to go next?",zh:"接下來要去哪你有推薦嗎？",cat:"travel",sc:"背包客棧交流",lv:1},

/* ============ 旅遊英文 · 網路與通訊 ============ */
{id:"t231",en:"Where can I buy a local SIM card?",zh:"我在哪裡可以買到當地的 SIM 卡？",cat:"travel",sc:"網路與通訊",lv:1},
{id:"t232",en:"Does this plan include international roaming?",zh:"這個方案有包含國際漫遊嗎？",cat:"travel",sc:"網路與通訊",lv:2,note:"roaming = 漫遊"},
{id:"t233",en:"Is there free Wi-Fi anywhere around here?",zh:"這附近有免費 Wi-Fi 嗎？",cat:"travel",sc:"網路與通訊",lv:1},
{id:"t234",en:"How many gigabytes does this plan come with?",zh:"這個方案有多少GB的流量？",cat:"travel",sc:"網路與通訊",lv:2},
{id:"t235",en:"My phone won't connect to the network.",zh:"我的手機一直連不上網路。",cat:"travel",sc:"網路與通訊",lv:1},
{id:"t236",en:"Can you top up my SIM card here?",zh:"可以在這裡幫我的 SIM 卡加值嗎？",cat:"travel",sc:"網路與通訊",lv:2,note:"top up = 加值、儲值"},
{id:"t237",en:"I need an eSIM instead of a physical one.",zh:"我需要 eSIM 而不是實體卡。",cat:"travel",sc:"網路與通訊",lv:2},
{id:"t238",en:"Is this Wi-Fi password case-sensitive?",zh:"這組 Wi-Fi 密碼有分大小寫嗎？",cat:"travel",sc:"網路與通訊",lv:2},
{id:"t239",en:"How do I check how much data I have left?",zh:"我要怎麼查還剩多少流量？",cat:"travel",sc:"網路與通訊",lv:2},
{id:"t240",en:"The signal here is really weak.",zh:"這裡的訊號很弱。",cat:"travel",sc:"網路與通訊",lv:1},

/* ============ 單字強化 · 決策 ============ */
{id:"v111",en:"I'm torn between the two options.",zh:"我在這兩個選項之間猶豫不決。",cat:"vocab",sc:"決策",lv:3,note:"torn = 猶豫不決、難以抉擇"},
{id:"v112",en:"Let's weigh the pros and cons first.",zh:"我們先權衡一下利弊吧。",cat:"vocab",sc:"決策",lv:2,note:"weigh = 權衡"},
{id:"v113",en:"I'll sleep on it and decide tomorrow.",zh:"我先想一晚，明天再決定。",cat:"vocab",sc:"決策",lv:2,note:"sleep on it = 考慮一晚再決定"},
{id:"v114",en:"I tend to overthink every decision.",zh:"我每個決定都容易想太多。",cat:"vocab",sc:"決策",lv:2},
{id:"v115",en:"Let's just go with your gut feeling.",zh:"就相信你的直覺吧。",cat:"vocab",sc:"決策",lv:2,note:"gut feeling = 直覺"},
{id:"v116",en:"I finally made up my mind.",zh:"我終於下定決心了。",cat:"vocab",sc:"決策",lv:1},
{id:"v117",en:"It's a tough call either way.",zh:"怎麼選都很難決定。",cat:"vocab",sc:"決策",lv:2,note:"a tough call = 難以抉擇的決定"},
{id:"v118",en:"I don't want to rush into anything.",zh:"我不想倉促做任何決定。",cat:"vocab",sc:"決策",lv:2},
{id:"v119",en:"We need to reach a decision by tonight.",zh:"我們今晚前得做出決定。",cat:"vocab",sc:"決策",lv:2},
{id:"v120",en:"In hindsight, I probably made the wrong call.",zh:"現在回想起來，我可能做錯決定了。",cat:"vocab",sc:"決策",lv:3,note:"in hindsight = 事後回想起來"},

/* ============ 單字強化 · 人際關係 ============ */
{id:"v121",en:"We've drifted apart over the years.",zh:"這些年我們漸行漸遠了。",cat:"vocab",sc:"人際關係",lv:3,note:"drift apart = 漸漸疏遠"},
{id:"v122",en:"He's someone I can really confide in.",zh:"他是我可以真正傾訴的對象。",cat:"vocab",sc:"人際關係",lv:3,note:"confide in = 向某人吐露心事"},
{id:"v123",en:"We patched things up after the fight.",zh:"我們吵架後和好了。",cat:"vocab",sc:"人際關係",lv:3,note:"patch things up = 和好、修補關係"},
{id:"v124",en:"She's always been there for me.",zh:"她一直都在我身邊支持我。",cat:"vocab",sc:"人際關係",lv:1},
{id:"v125",en:"We just clicked right from the start.",zh:"我們一開始就一拍即合。",cat:"vocab",sc:"人際關係",lv:3,note:"click = 一拍即合、相處融洽"},
{id:"v126",en:"I don't want to burn any bridges.",zh:"我不想把關係鬧僵。",cat:"vocab",sc:"人際關係",lv:3,note:"burn bridges = 斷絕關係、把事情鬧僵"},
{id:"v127",en:"It takes time to build trust.",zh:"建立信任需要時間。",cat:"vocab",sc:"人際關係",lv:1},
{id:"v128",en:"We had a bit of a falling out last year.",zh:"我們去年鬧翻了一陣子。",cat:"vocab",sc:"人際關係",lv:3,note:"falling out = 爭執、鬧翻"},
{id:"v129",en:"He's really easy to get along with.",zh:"他真的很好相處。",cat:"vocab",sc:"人際關係",lv:1},
{id:"v130",en:"I value our friendship a lot.",zh:"我很珍惜我們的友誼。",cat:"vocab",sc:"人際關係",lv:1},

/* ============ 單字強化 · 環境 ============ */
{id:"v131",en:"Pollution levels have gotten worse in the city.",zh:"城市裡的污染程度變得更嚴重了。",cat:"vocab",sc:"環境",lv:2},
{id:"v132",en:"We need to reduce our carbon footprint.",zh:"我們需要減少碳足跡。",cat:"vocab",sc:"環境",lv:3,note:"carbon footprint = 碳足跡"},
{id:"v133",en:"The forest has been shrinking every year.",zh:"這片森林每年都在縮小。",cat:"vocab",sc:"環境",lv:2},
{id:"v134",en:"Renewable energy is becoming more common.",zh:"再生能源變得越來越普遍。",cat:"vocab",sc:"環境",lv:3,note:"renewable energy = 再生能源"},
{id:"v135",en:"Plastic waste ends up in the ocean.",zh:"塑膠垃圾最終流入海洋。",cat:"vocab",sc:"環境",lv:2},
{id:"v136",en:"The government is pushing for greener policies.",zh:"政府正在推動更環保的政策。",cat:"vocab",sc:"環境",lv:3},
{id:"v137",en:"Extreme weather is becoming more frequent.",zh:"極端天氣變得越來越頻繁。",cat:"vocab",sc:"環境",lv:2},
{id:"v138",en:"We should conserve water whenever we can.",zh:"我們應該盡量節約用水。",cat:"vocab",sc:"環境",lv:2,note:"conserve = 節約、保護"},
{id:"v139",en:"Wildlife habitats are shrinking fast.",zh:"野生動物棲息地正快速縮減。",cat:"vocab",sc:"環境",lv:3,note:"habitat = 棲息地"},
{id:"v140",en:"Sustainability should be everyone's responsibility.",zh:"永續發展應該是每個人的責任。",cat:"vocab",sc:"環境",lv:3},

/* ============ 單字強化 · 財務 ============ */
{id:"v141",en:"I need to keep better track of my expenses.",zh:"我需要更仔細追蹤我的開銷。",cat:"vocab",sc:"財務",lv:2},
{id:"v142",en:"That purchase was a total waste of money.",zh:"那筆花費根本是浪費錢。",cat:"vocab",sc:"財務",lv:1},
{id:"v143",en:"I'm trying to live within my means.",zh:"我在努力量入為出。",cat:"vocab",sc:"財務",lv:3,note:"live within one's means = 量入為出"},
{id:"v144",en:"He's always in debt somehow.",zh:"他不知怎麼總是負債。",cat:"vocab",sc:"財務",lv:2},
{id:"v145",en:"I got a great deal on this.",zh:"我這個買得很划算。",cat:"vocab",sc:"財務",lv:1,note:"a great deal = 很划算的交易"},
{id:"v146",en:"Prices have gone up a lot recently.",zh:"最近物價漲了不少。",cat:"vocab",sc:"財務",lv:1},
{id:"v147",en:"I'd rather invest than let my money sit idle.",zh:"我寧願投資也不要讓錢閒置。",cat:"vocab",sc:"財務",lv:3,note:"sit idle = 閒置不用"},
{id:"v148",en:"We're on a pretty tight budget this month.",zh:"我們這個月預算抓得很緊。",cat:"vocab",sc:"財務",lv:2},
{id:"v149",en:"That's way overpriced for what it is.",zh:"以它的品質來說這價格貴太多了。",cat:"vocab",sc:"財務",lv:2,note:"overpriced = 定價過高"},
{id:"v150",en:"I finally paid off all my debt.",zh:"我終於把所有債務都還清了。",cat:"vocab",sc:"財務",lv:2}

]);
